import {
  LayoutDashboard,
  Users,
  Calendar,
  Workflow,
  FileText,
  BarChart3,
  Brain,
  Shield,
  UserPlus,
  Upload,
  GraduationCap,
  Target,
  Heart,
  MonitorCheck,
  MessageCircle,
  ClipboardList,
  CalendarClock,
  Clock,
  Clipboard,
  Award,
  FolderKanban,
  BookOpen,
  TrendingUp,
  FileCheck,
  Compass,
  Crown,
  Lightbulb,
  BriefcaseBusiness,
  Pin,
  Wrench,
  Package,
  Stethoscope,
  Network,
  Sparkles,
  Contact,
  ClipboardCheck,
  LineChart,
  Settings,
} from "lucide-react"
import type { HelpArticle, FAQ, VideoTutorial, LearningPath, HelpCategory } from "./types"

// ─── CATEGORIES ── aligned with actual sidebar navigation groups ───
export const helpCategories: HelpCategory[] = [
  {
    id: "overview",
    name: "Übersicht",
    icon: LayoutDashboard,
    color: "text-blue-600",
    bgColor: "bg-blue-500/10",
    borderColor: "border-blue-500/20",
    gradient: "from-blue-500 to-cyan-500",
    description: "Dashboard, KI-Analyse, Academy & Schwarzes Brett",
    articleCount: 6,
  },
  {
    id: "planning",
    name: "Planung & Organisation",
    icon: CalendarClock,
    color: "text-amber-600",
    bgColor: "bg-amber-500/10",
    borderColor: "border-amber-500/20",
    gradient: "from-amber-500 to-orange-500",
    description: "Kalender, Dienstplan, Zeiterfassung, Aufgaben, Ziele, Workflows & Zuständigkeiten",
    articleCount: 8,
  },
  {
    id: "data",
    name: "Daten & Dokumente",
    icon: FileText,
    color: "text-rose-600",
    bgColor: "bg-rose-500/10",
    borderColor: "border-rose-500/20",
    gradient: "from-rose-500 to-red-500",
    description: "Kennzahlen, Dokumente, Journal & Protokolle",
    articleCount: 5,
  },
  {
    id: "quality",
    name: "Qualitätsmanagement",
    icon: Shield,
    color: "text-emerald-600",
    bgColor: "bg-emerald-500/10",
    borderColor: "border-emerald-500/20",
    gradient: "from-emerald-500 to-teal-500",
    description: "Wissen/QM-Handbuch, Verbesserungsmeldungen (CIRS) & Hygieneplan",
    articleCount: 4,
  },
  {
    id: "strategy",
    name: "Strategie & Führung",
    icon: Compass,
    color: "text-indigo-600",
    bgColor: "bg-indigo-500/10",
    borderColor: "border-indigo-500/20",
    gradient: "from-indigo-500 to-blue-500",
    description: "Strategiepfad, Leadership, Wellbeing, Leitbild, ROI, IGeL, Konkurrenz & Wunschpatient",
    articleCount: 9,
  },
  {
    id: "team",
    name: "Team & Personal",
    icon: Users,
    color: "text-teal-600",
    bgColor: "bg-teal-500/10",
    borderColor: "border-teal-500/20",
    gradient: "from-teal-500 to-emerald-500",
    description: "Personalsuche, Team, Mitarbeitergespräche, Selbst-Check, Kompetenzen, Organigramm & Fortbildung",
    articleCount: 8,
  },
  {
    id: "praxis",
    name: "Praxis & Einstellungen",
    icon: Settings,
    color: "text-slate-600",
    bgColor: "bg-slate-500/10",
    borderColor: "border-slate-500/20",
    gradient: "from-slate-500 to-gray-500",
    description: "Kontakte, Umfragen, Arbeitsplätze, Räume, Arbeitsmittel, Material, Geräte & Einstellungen",
    articleCount: 9,
  },
]

// ─── ARTICLES ── one per sidebar item, grouped by navigation group ───
export const helpArticles: HelpArticle[] = [
  // ── Übersicht ──
  {
    id: "1",
    title: "Dashboard: Ihr Cockpit auf einen Blick",
    description: "So konfigurieren Sie Widgets, sehen offene Aufgaben und verfolgen KPIs direkt im Dashboard.",
    category: "Übersicht",
    categoryId: "overview",
    content: "Unter /dashboard sehen Sie alle wichtigen Informationen auf einen Blick. Klicken Sie auf das Zahnrad-Symbol, um das Cockpit zu bearbeiten: Widgets ein-/ausschalten, die Spaltenbreite pro Karte festlegen und per Drag & Drop die Reihenfolge ändern. Verfügbare Widgets: Offene Aufgaben, Termine heute, Aktive Kandidaten, Google-Bewertungen, Schwarzes Brett, Journal-Handlungsempfehlungen, KPIs, Todos und mehr.",
    readTime: 6,
    difficulty: "beginner",
    tags: ["Dashboard", "Cockpit", "Widgets", "KPIs"],
    views: 5210,
    helpful: 412,
    lastUpdated: "2026-02-15",
    author: "Effizienz Praxis Team",
  },
  {
    id: "2",
    title: "KI-Analyse: Automatische Praxis-Bewertung",
    description: "Die KI analysiert alle Praxisdaten und generiert einen Praxis-Score mit Handlungsempfehlungen.",
    category: "Übersicht",
    categoryId: "overview",
    content: "Unter /analysis starten Sie eine umfassende KI-Analyse. Das System bewertet über 60 Datenpunkte: Team, Finanzen, Hygiene, CIRS, Fortbildung, Kommunikation, Geräte und mehr. Sie erhalten einen Praxis-Score (0-100), detaillierte Kategorie-Bewertungen und priorisierte Empfehlungen. Die Analyse kann jederzeit wiederholt werden, um Fortschritte zu messen.",
    readTime: 8,
    difficulty: "beginner",
    tags: ["KI", "Analyse", "Praxis-Score", "Empfehlungen"],
    views: 4560,
    helpful: 378,
    lastUpdated: "2026-02-18",
    author: "Effizienz Praxis Team",
  },
  {
    id: "3",
    title: "Academy: Online-Kurse und Gamification",
    description: "Lernplattform mit Kursen, Quizzes, Badges und Rangliste für Ihr Praxisteam.",
    category: "Übersicht",
    categoryId: "overview",
    content: "Unter /academy finden Sie Fortbildungskurse zu Praxismanagement, QM, Hygiene und mehr. Features: Kursfortschritt mit XP und Levels, Quizzes mit sofortigem Feedback, Badges/Abzeichen sammeln, Rangliste im Team, Lern-Streaks. Kurse können vom Super-Admin erstellt oder per KI generiert werden. Mitarbeiter sehen ihren Fortschritt unter 'Mein Lernen'.",
    readTime: 8,
    difficulty: "beginner",
    tags: ["Academy", "Kurse", "Fortbildung", "Gamification", "Badges"],
    views: 2890,
    helpful: 234,
    lastUpdated: "2026-02-18",
  },
  {
    id: "4",
    title: "Schwarzes Brett: Interne Mitteilungen",
    description: "Erstellen Sie Beiträge mit Kategorien, Prioritäten, Anhängen und Lesebestätigungen für Ihr Team.",
    category: "Übersicht",
    categoryId: "overview",
    content: "Unter /schwarzes-brett erstellen und verwalten Sie interne Mitteilungen. Features: Beiträge nach Orga-Kategorien filtern, Priorität (Hoch/Mittel/Niedrig) setzen, Beiträge anheften, Lesebestätigung anfordern, Dateien anhängen, Kachel- oder Listenansicht. Angeheftete und neue Beiträge erscheinen auch als Widgets im Dashboard.",
    readTime: 6,
    difficulty: "beginner",
    tags: ["Schwarzes Brett", "Mitteilungen", "Kommunikation", "Lesebestätigung"],
    views: 3120,
    helpful: 256,
    lastUpdated: "2026-02-18",
  },

  // ── Planung & Organisation ──
  {
    id: "10",
    title: "Kalender: Termine und Terminplanung",
    description: "Erstellen Sie Termine, weisen Sie Räume und Mitarbeiter zu und nutzen Sie Tages-/Wochen-/Monatsansicht.",
    category: "Planung & Organisation",
    categoryId: "planning",
    content: "Unter /calendar verwalten Sie alle Termine. Erstellen Sie Einzel- oder wiederkehrende Termine, weisen Sie Räume und verantwortliche Mitarbeiter zu. Verschiedene Ansichten (Tag, Woche, Monat) und Farbcodes für Terminarten. Verknüpfung mit Dienstplan und Ressourcenplanung.",
    readTime: 10,
    difficulty: "beginner",
    tags: ["Kalender", "Termine", "Planung", "Räume"],
    views: 3450,
    helpful: 278,
    lastUpdated: "2026-02-15",
  },
  {
    id: "11",
    title: "Dienstplan: Schichtplanung für Ihr Team",
    description: "Erstellen Sie Dienstpläne per Drag & Drop mit automatischen Vorschlägen und Urlaubsberücksichtigung.",
    category: "Planung & Organisation",
    categoryId: "planning",
    content: "Unter /dienstplan erstellen Sie Schichtpläne per Drag & Drop. Das System berücksichtigt Arbeitsverträge, Urlaubsanträge und Qualifikationen. KI-Vorschläge für optimale Besetzung. Warnung bei Unterbesetzung. Export als PDF.",
    readTime: 12,
    difficulty: "intermediate",
    tags: ["Dienstplan", "Schichtplanung", "Urlaub", "Besetzung"],
    views: 3120,
    helpful: 267,
    lastUpdated: "2026-02-15",
  },
  {
    id: "12",
    title: "Zeiterfassung: Arbeitszeiten und Berichte",
    description: "Stempeluhr für Mitarbeiter, Manager-Übersicht und Export für die Lohnabrechnung.",
    category: "Planung & Organisation",
    categoryId: "planning",
    content: "Unter /zeiterfassung stempeln Mitarbeiter Beginn und Ende ihrer Arbeitszeit. Manager sehen eine Übersicht aller Zeiten. Erstellen Sie Berichte nach Zeitraum, Mitarbeiter oder Abteilung. Export als CSV/PDF für die Lohnabrechnung.",
    readTime: 8,
    difficulty: "beginner",
    tags: ["Zeiterfassung", "Arbeitszeit", "Stempeluhr", "Berichte", "Export"],
    views: 2890,
    helpful: 234,
    lastUpdated: "2026-02-10",
  },
  {
    id: "13",
    title: "Aufgaben: Todos erstellen und delegieren",
    description: "Erstellen, zuweisen und verfolgen Sie Aufgaben mit Prioritäten, Fristen und Filtern.",
    category: "Planung & Organisation",
    categoryId: "planning",
    content: "Unter /todos verwalten Sie alle Aufgaben. Setzen Sie Prioritäten (Hoch/Mittel/Niedrig), Fälligkeitsdaten und weisen Sie Aufgaben an Teammitglieder zu. Filtern Sie nach 'Wichtig' oder 'Dringend'. Offene Aufgaben erscheinen im Dashboard-Widget.",
    readTime: 7,
    difficulty: "beginner",
    tags: ["Aufgaben", "Todos", "Delegation", "Prioritäten"],
    views: 3780,
    helpful: 312,
    lastUpdated: "2026-02-12",
  },
  {
    id: "14",
    title: "Ziele: KPIs setzen und Fortschritt messen",
    description: "Definieren Sie Team- und Praxisziele mit messbaren Kennzahlen und visueller Fortschrittsverfolgung.",
    category: "Planung & Organisation",
    categoryId: "planning",
    content: "Unter /goals erstellen Sie Ziele mit Beschreibung, Zielwert und Frist. Verknüpfen Sie Ziele mit KPIs. Das Dashboard zeigt den Fortschritt aller aktiven Ziele. Mitarbeiter können eigene Teilziele erstellen.",
    readTime: 8,
    difficulty: "intermediate",
    tags: ["Ziele", "KPIs", "Fortschritt", "Performance"],
    views: 2340,
    helpful: 198,
    lastUpdated: "2026-02-10",
  },
  {
    id: "15",
    title: "Workflows: Prozesse standardisieren",
    description: "Erstellen Sie wiederverwendbare Workflow-Vorlagen mit Schritten, Checklisten und Automatisierung.",
    category: "Planung & Organisation",
    categoryId: "planning",
    content: "Unter /workflows erstellen Sie Vorlagen für wiederkehrende Prozesse (Praxisöffnung, Gerätewartung, Patientenaufnahme). Jeder Workflow besteht aus Schritten mit Verantwortlichen, Fristen und Checklisten. Workflows können manuell oder per Zeitplan gestartet werden.",
    readTime: 12,
    difficulty: "intermediate",
    tags: ["Workflows", "Checklisten", "Automatisierung", "Prozesse"],
    views: 2560,
    helpful: 212,
    lastUpdated: "2026-02-14",
  },
  {
    id: "16",
    title: "Zuständigkeiten: Verantwortungsbereiche definieren",
    description: "Klare Zuordnung wer für welche Bereiche verantwortlich ist.",
    category: "Planung & Organisation",
    categoryId: "planning",
    content: "Unter /responsibilities definieren Sie, wer für welche Bereiche (z.B. Hygiene, Geräte, Labor) verantwortlich ist. Das System verknüpft Zuständigkeiten automatisch mit relevanten Workflows und Aufgaben.",
    readTime: 6,
    difficulty: "beginner",
    tags: ["Zuständigkeiten", "Verantwortung", "Organisation"],
    views: 1890,
    helpful: 156,
    lastUpdated: "2026-02-08",
  },

  // ── Daten & Dokumente ──
  {
    id: "20",
    title: "Kennzahlen: Praxisauswertung und Dashboards",
    description: "Anpassbare KPI-Dashboards mit Diagrammen, Trends und Benchmarks.",
    category: "Daten & Dokumente",
    categoryId: "data",
    content: "Unter /analytics sehen Sie Ihre wichtigsten Kennzahlen in anpassbaren Dashboards. Erstellen Sie benutzerdefinierte Diagramme, vergleichen Sie Zeiträume und exportieren Sie Berichte als PDF/CSV.",
    readTime: 10,
    difficulty: "intermediate",
    tags: ["Kennzahlen", "KPIs", "Analytics", "Diagramme", "Berichte"],
    views: 3450,
    helpful: 289,
    lastUpdated: "2026-02-15",
  },
  {
    id: "21",
    title: "Dokumente: Zentrale Dokumentenverwaltung",
    description: "Laden Sie Dokumente hoch, organisieren Sie in Ordnern und nutzen Sie Tags und Suche.",
    category: "Daten & Dokumente",
    categoryId: "data",
    content: "Unter /documents laden Sie Dokumente hoch und organisieren sie in Ordnern. Nutzen Sie Tags und Volltextsuche. Dokumente können als Vorlagen bereitgestellt oder mit Workflows verknüpft werden.",
    readTime: 8,
    difficulty: "beginner",
    tags: ["Dokumente", "Upload", "Ordner", "Tags", "Suche"],
    views: 2890,
    helpful: 245,
    lastUpdated: "2026-02-12",
  },
  {
    id: "22",
    title: "Journal: KI-Insights und Handlungsempfehlungen",
    description: "Automatisch generierte Erkenntnisse und Empfehlungen basierend auf Ihren Praxisdaten.",
    category: "Daten & Dokumente",
    categoryId: "data",
    content: "Unter /practice-insights sehen Sie KI-generierte Journal-Einträge mit Handlungsempfehlungen. Die Empfehlungen werden nach Priorität (Hoch/Mittel/Niedrig) sortiert und erscheinen auch als Widget im Dashboard.",
    readTime: 7,
    difficulty: "beginner",
    tags: ["Journal", "KI-Insights", "Handlungsempfehlungen"],
    views: 2450,
    helpful: 212,
    lastUpdated: "2026-02-18",
  },
  {
    id: "23",
    title: "Protokolle: Besprechungen dokumentieren",
    description: "Strukturierte Protokolle für Teamsitzungen, Besprechungen und Meetings erstellen.",
    category: "Daten & Dokumente",
    categoryId: "data",
    content: "Unter /protocols erstellen Sie Protokolle mit Vorlage, Teilnehmern und Tagesordnungspunkten. Die KI kann Protokolle automatisch aus Notizen generieren. Protokolle werden archiviert und sind durchsuchbar.",
    readTime: 7,
    difficulty: "beginner",
    tags: ["Protokolle", "Besprechung", "Dokumentation", "Meeting"],
    views: 2450,
    helpful: 198,
    lastUpdated: "2026-02-10",
  },

  // ── Qualitätsmanagement ──
  {
    id: "30",
    title: "Wissen: QM-Handbuch und SOPs",
    description: "Erstellen und pflegen Sie Ihr QM-Handbuch mit Standard Operating Procedures.",
    category: "Qualitätsmanagement",
    categoryId: "quality",
    content: "Unter /knowledge verwalten Sie Ihr QM-Handbuch mit allen SOPs (Standard Operating Procedures). Erstellen Sie Einträge mit Kategorien, verknüpfen Sie mit Workflows und teilen Sie Wissen im Team. Versionierung und Freigabeprozesse inklusive.",
    readTime: 10,
    difficulty: "intermediate",
    tags: ["QM-Handbuch", "SOPs", "Wissen", "Qualitätsmanagement"],
    views: 2890,
    helpful: 245,
    lastUpdated: "2026-02-15",
  },
  {
    id: "31",
    title: "Verbesserungsmeldungen (CIRS): Fehler anonym melden",
    description: "Critical Incident Reporting System für anonyme Meldungen und systematische Auswertung.",
    category: "Qualitätsmanagement",
    categoryId: "quality",
    content: "Unter /cirs melden Mitarbeiter Beinahe-Fehler und Zwischenfälle anonym. Das System unterstützt Schweregrad-Einstufung, systematische Auswertung und Ableitung von Verbesserungsmaßnahmen. Die KI-Analyse berücksichtigt offene CIRS-Meldungen im Praxis-Score.",
    readTime: 10,
    difficulty: "intermediate",
    tags: ["CIRS", "Fehlermeldung", "Patientensicherheit", "QM", "Anonym"],
    views: 1890,
    helpful: 167,
    lastUpdated: "2026-02-12",
  },
  {
    id: "32",
    title: "Hygieneplan: Reinigung und Kontrollen",
    description: "Erstellen Sie Hygienepläne, dokumentieren Sie Durchführungen und generieren Sie Nachweise.",
    category: "Qualitätsmanagement",
    categoryId: "quality",
    content: "Unter /hygieneplan verwalten Sie alle hygienerelevanten Pläne und Durchführungen. Erstellen Sie Reinigungspläne mit Intervallen, dokumentieren Sie Begehungen und generieren Sie Compliance-Nachweise. Die Hygiene-Compliance-Rate fließt in die KI-Analyse ein.",
    readTime: 10,
    difficulty: "intermediate",
    tags: ["Hygieneplan", "Reinigung", "Kontrollen", "Compliance", "Begehung"],
    views: 3210,
    helpful: 267,
    lastUpdated: "2026-02-15",
  },

  // ── Strategie & Führung ──
  {
    id: "40",
    title: "Strategiepfad: Geführte Strategieentwicklung",
    description: "Durchlaufen Sie einen strukturierten Prozess zur Definition Ihrer Praxisstrategie.",
    category: "Strategie & Führung",
    categoryId: "strategy",
    content: "Unter /strategy-journey durchlaufen Sie einen geführten Prozess zur Strategieentwicklung. Definieren Sie Vision, Mission und strategische Ziele. Die Ergebnisse fließen in Ihre Zielsetzung und KPI-Planung ein.",
    readTime: 15,
    difficulty: "advanced",
    tags: ["Strategie", "Vision", "Mission", "Planung"],
    views: 1560,
    helpful: 134,
    lastUpdated: "2026-02-10",
  },
  {
    id: "41",
    title: "Leadership: Führungskompetenzen entwickeln",
    description: "Tools und Ressourcen zur Entwicklung Ihrer Führungsfähigkeiten in der Praxis.",
    category: "Strategie & Führung",
    categoryId: "strategy",
    content: "Unter /leadership finden Sie Tools zur Führungskräfteentwicklung: Selbsteinschätzung, Führungsstile, Kommunikationstechniken und Team-Management-Strategien. Verknüpft mit Mitarbeitergesprächen und Wellbeing.",
    readTime: 12,
    difficulty: "intermediate",
    tags: ["Leadership", "Führung", "Management", "Entwicklung"],
    views: 1780,
    helpful: 145,
    lastUpdated: "2026-02-08",
  },
  {
    id: "42",
    title: "Mitarbeiter-Wellbeing: Stimmung und Teamklima",
    description: "Verfolgen Sie die Team-Stimmung, erkennen Sie Belastungsspitzen und stärken Sie das Teamklima.",
    category: "Strategie & Führung",
    categoryId: "strategy",
    content: "Unter /wellbeing sehen Mitarbeiter ihren persönlichen Wellbeing-Status. Manager erhalten anonymisierte Teamdaten. Features: Stimmungsabfragen, Kudos/Lob, Arbeitsbelastungsanzeige. Das System erkennt Trends und warnt bei kritischen Mustern.",
    readTime: 8,
    difficulty: "beginner",
    tags: ["Wellbeing", "Stimmung", "Teamklima", "Kudos"],
    views: 2450,
    helpful: 212,
    lastUpdated: "2026-02-15",
  },
  {
    id: "43",
    title: "Leitbild: Vision und Werte formulieren",
    description: "Erstellen Sie Ihr Praxis-Leitbild mit KI-Unterstützung und teilen Sie es im Team.",
    category: "Strategie & Führung",
    categoryId: "strategy",
    content: "Unter /leitbild führt Sie ein geführter Prozess durch die Erstellung. Die KI unterstützt bei der Formulierung von Vision, Mission und Werten. Sie können das Leitbild mit Ihrem Team teilen und in die Strategieplanung einbinden.",
    readTime: 10,
    difficulty: "intermediate",
    tags: ["Leitbild", "Vision", "Mission", "Werte"],
    views: 1560,
    helpful: 134,
    lastUpdated: "2026-02-08",
  },
  {
    id: "44",
    title: "Lohnt-es-sich-Analyse: ROI berechnen",
    description: "Bewerten Sie die Wirtschaftlichkeit von Investitionen und Leistungen mit ROI-Berechnung.",
    category: "Strategie & Führung",
    categoryId: "strategy",
    content: "Unter /roi-analysis berechnen Sie den Return on Investment für Anschaffungen, neue Leistungen oder Prozessänderungen. Die KI unterstützt bei der Schätzung von Kosten und Nutzen.",
    readTime: 10,
    difficulty: "advanced",
    tags: ["ROI", "Wirtschaftlichkeit", "Investition", "Analyse"],
    views: 1890,
    helpful: 167,
    lastUpdated: "2026-02-10",
  },
  {
    id: "45",
    title: "Selbstzahler-Analyse: IGeL bewerten",
    description: "Analysieren Sie Potenzial und Profitabilität individueller Gesundheitsleistungen.",
    category: "Strategie & Führung",
    categoryId: "strategy",
    content: "Unter /igel-analysis analysieren Sie das Potenzial von IGeL-Leistungen. Die KI berechnet Marktpotenzial und gibt Empfehlungen zu Preisgestaltung und Marketing. Vergleichen Sie verschiedene Leistungen nach Profitabilität.",
    readTime: 12,
    difficulty: "advanced",
    tags: ["IGeL", "Selbstzahler", "Analyse", "Profitabilität"],
    views: 1780,
    helpful: 145,
    lastUpdated: "2026-02-08",
  },
  {
    id: "46",
    title: "Konkurrenzanalyse: Mitbewerber vergleichen",
    description: "Vergleichen Sie Ihre Praxis mit Mitbewerbern und identifizieren Sie Differenzierungspotenziale.",
    category: "Strategie & Führung",
    categoryId: "strategy",
    content: "Unter /competitor-analysis erstellen Sie eine Analyse. Die KI sammelt öffentlich verfügbare Daten zu Mitbewerbern: Leistungsspektrum, Google-Bewertungen, Online-Präsenz. Sie erhalten eine SWOT-Analyse mit Handlungsempfehlungen.",
    readTime: 15,
    difficulty: "advanced",
    tags: ["Konkurrenz", "SWOT", "Wettbewerb", "Vergleich"],
    views: 2120,
    helpful: 178,
    lastUpdated: "2026-02-10",
  },
  {
    id: "47",
    title: "Wunschpatient: Ideale Zielgruppe definieren",
    description: "Erstellen Sie detaillierte Profile Ihrer Zielgruppe für gezieltes Marketing.",
    category: "Strategie & Führung",
    categoryId: "strategy",
    content: "Unter /wunschpatient erstellen Sie Profile Ihrer idealen Patienten. Die KI analysiert Ihre Patientenstruktur und gibt Empfehlungen zur optimalen Positionierung. Verknüpfen Sie mit Ihrer Marketing-Strategie.",
    readTime: 10,
    difficulty: "intermediate",
    tags: ["Wunschpatient", "Zielgruppe", "Marketing", "Positionierung"],
    views: 1780,
    helpful: 145,
    lastUpdated: "2026-02-08",
  },

  // ── Team & Personal ──
  {
    id: "50",
    title: "Personalsuche: Stellenausschreibungen und Kandidaten",
    description: "Erstellen Sie Stellenanzeigen, verwalten Sie Bewerbungen und verfolgen Sie den Recruiting-Prozess.",
    category: "Team & Personal",
    categoryId: "team",
    content: "Unter /hiring verwalten Sie offene Stellen und Bewerbungen. Erstellen Sie Stellenausschreibungen, erfassen Sie Kandidaten mit Status (Neu/Kontaktiert/Interview/Angebot), VERAH/NaPa-Kennzeichnung und Notizen. Das Dashboard zeigt aktive Kandidaten als Widget.",
    readTime: 10,
    difficulty: "intermediate",
    tags: ["Personalsuche", "Recruiting", "Stellenanzeige", "Kandidaten", "VERAH", "NaPa"],
    views: 2340,
    helpful: 198,
    lastUpdated: "2026-02-18",
  },
  {
    id: "51",
    title: "Team: Mitarbeiter verwalten und einladen",
    description: "Fügen Sie Teammitglieder hinzu, weisen Sie Rollen zu und verwalten Sie Zugriffsrechte.",
    category: "Team & Personal",
    categoryId: "team",
    content: "Unter /team sehen Sie alle Teammitglieder. Klicken Sie auf 'Mitarbeiter hinzufügen', geben Sie E-Mail und Rolle ein (Praxisinhaber, Arzt, Praxismanager, MFA, Auszubildende). Jede Rolle hat vordefinierte Berechtigungen, die angepasst werden können.",
    readTime: 7,
    difficulty: "beginner",
    tags: ["Team", "Mitarbeiter", "Rollen", "Berechtigungen", "Einladung"],
    views: 4120,
    helpful: 356,
    lastUpdated: "2026-02-15",
  },
  {
    id: "52",
    title: "Mitarbeitergespräche: Feedback strukturiert führen",
    description: "Planen Sie Gespräche mit Vorlagen, Bewertungskriterien und automatischen Erinnerungen.",
    category: "Team & Personal",
    categoryId: "team",
    content: "Unter /mitarbeitergespraeche erstellen Sie Gesprächsvorlagen mit Bewertungskriterien. Planen Sie Jahres-, Halbjahres- oder Quartalsgespräche. Die KI schlägt Gesprächspunkte basierend auf aktuellen Zielen und Performance-Daten vor.",
    readTime: 12,
    difficulty: "intermediate",
    tags: ["Mitarbeitergespräche", "Feedback", "Bewertung", "Planung"],
    views: 2670,
    helpful: 234,
    lastUpdated: "2026-02-12",
  },
  {
    id: "53",
    title: "Selbst-Check: Praxis-Effizienz bewerten",
    description: "Strukturierter Fragebogen zur Selbstbewertung mit KI-gestützter Auswertung.",
    category: "Team & Personal",
    categoryId: "team",
    content: "Unter /selbst-check beantworten Sie einen Fragebogen zu verschiedenen Praxisbereichen. Die KI wertet Ihre Antworten aus und erstellt einen detaillierten Bericht mit Handlungsempfehlungen. Vergleichen Sie Ergebnisse über die Zeit.",
    readTime: 8,
    difficulty: "beginner",
    tags: ["Selbst-Check", "Effizienz", "Bewertung", "Fragebogen"],
    views: 2340,
    helpful: 198,
    lastUpdated: "2026-02-10",
  },
  {
    id: "54",
    title: "Kompetenzen: Skills im Team verfolgen",
    description: "Erfassen Sie Qualifikationen, Zertifizierungen und Fortbildungsbedarfe Ihrer Mitarbeiter.",
    category: "Team & Personal",
    categoryId: "team",
    content: "Unter /skills verwalten Sie Kompetenzkategorien und weisen Mitarbeitern Fähigkeiten zu. Das System erinnert an ablaufende Zertifikate und empfiehlt passende Fortbildungen aus der Academy.",
    readTime: 10,
    difficulty: "intermediate",
    tags: ["Skills", "Kompetenzen", "Zertifikate", "Fortbildung"],
    views: 2340,
    helpful: 187,
    lastUpdated: "2026-02-10",
  },
  {
    id: "55",
    title: "Organigramm: Teamstruktur visualisieren",
    description: "Interaktives Organigramm mit Hierarchien, Abteilungen und Verantwortlichkeiten.",
    category: "Team & Personal",
    categoryId: "team",
    content: "Unter /organigramm wird automatisch eine visuelle Darstellung Ihrer Teamstruktur generiert. Per Drag & Drop passen Sie Hierarchien und Abteilungen an. Export als PDF möglich.",
    readTime: 5,
    difficulty: "beginner",
    tags: ["Organigramm", "Teamstruktur", "Organisation", "Hierarchie"],
    views: 1890,
    helpful: 156,
    lastUpdated: "2026-02-08",
  },
  {
    id: "56",
    title: "Fortbildung: Schulungen und Kurse verwalten",
    description: "Verwalten Sie Fortbildungspläne, Schulungsnachweise und Zertifizierungen.",
    category: "Team & Personal",
    categoryId: "team",
    content: "Unter /training verwalten Sie Fortbildungskurse und -events. Planen Sie Schulungen, erfassen Sie Teilnahmen und Zertifikate. Bevorstehende Events und Fortbildungsaktivität fließen in die KI-Analyse ein.",
    readTime: 8,
    difficulty: "intermediate",
    tags: ["Fortbildung", "Schulung", "Zertifikate", "Training"],
    views: 2120,
    helpful: 178,
    lastUpdated: "2026-02-12",
  },

  // ── Praxis & Einstellungen ──
  {
    id: "60",
    title: "Kontakte: Externe Kontakte verwalten",
    description: "Verwalten Sie Lieferanten, Labore, Dienstleister und andere externe Kontakte.",
    category: "Praxis & Einstellungen",
    categoryId: "praxis",
    content: "Unter /contacts verwalten Sie alle externen Kontakte Ihrer Praxis: Lieferanten, Labore, Dienstleister, Kooperationspartner. Speichern Sie Kontaktdaten, Notizen und verknüpfen Sie Kontakte mit Bestellungen oder Geräten.",
    readTime: 6,
    difficulty: "beginner",
    tags: ["Kontakte", "Lieferanten", "Labore", "Dienstleister"],
    views: 1560,
    helpful: 123,
    lastUpdated: "2026-02-08",
  },
  {
    id: "61",
    title: "Umfragen: Team-Feedback einholen",
    description: "Erstellen Sie anonyme oder persönliche Umfragen mit Echtzeit-Auswertung.",
    category: "Praxis & Einstellungen",
    categoryId: "praxis",
    content: "Unter /surveys erstellen Sie Umfragen mit verschiedenen Fragetypen (Single/Multi-Choice, Freitext, Skala). Teilen Sie per Link oder QR-Code. Auswertung in Echtzeit mit Diagrammen und Trends. Option für anonyme Teilnahme.",
    readTime: 8,
    difficulty: "intermediate",
    tags: ["Umfragen", "Feedback", "Zufriedenheit", "Auswertung"],
    views: 2670,
    helpful: 223,
    lastUpdated: "2026-02-12",
  },
  {
    id: "62",
    title: "Arbeitsplätze: Arbeitsplätze verwalten",
    description: "Erstellen Sie einen digitalen Plan Ihrer Arbeitsplätze und deren Ausstattung.",
    category: "Praxis & Einstellungen",
    categoryId: "praxis",
    content: "Unter /arbeitsplaetze verwalten Sie alle Arbeitsplätze in Ihrer Praxis. Ordnen Sie Arbeitsplätze Räumen zu, dokumentieren Sie die Ausstattung und verknüpfen Sie mit Mitarbeitern.",
    readTime: 5,
    difficulty: "beginner",
    tags: ["Arbeitsplätze", "Ausstattung", "Organisation"],
    views: 1230,
    helpful: 98,
    lastUpdated: "2026-02-05",
  },
  {
    id: "63",
    title: "Räume: Raumverwaltung und Raumplan",
    description: "Verwalten Sie Praxisräume mit Ausstattung, Kapazität und Terminverknüpfung.",
    category: "Praxis & Einstellungen",
    categoryId: "praxis",
    content: "Unter /rooms verwalten Sie Ihre Praxisräume mit Ausstattung und Kapazität. Verknüpfen Sie Räume mit Terminen und Ressourcenplanung.",
    readTime: 5,
    difficulty: "beginner",
    tags: ["Räume", "Raumplan", "Ausstattung", "Kapazität"],
    views: 1560,
    helpful: 123,
    lastUpdated: "2026-02-05",
  },
  {
    id: "64",
    title: "Arbeitsmittel: Werkzeuge und Hilfsmittel",
    description: "Erfassen und verwalten Sie Arbeitsmittel mit Zuweisungen und Wartungsintervallen.",
    category: "Praxis & Einstellungen",
    categoryId: "praxis",
    content: "Unter /arbeitsmittel erfassen Sie alle Werkzeuge und Hilfsmittel. Weisen Sie Arbeitsmittel Mitarbeitern oder Räumen zu, verfolgen Sie Wartungsintervalle und dokumentieren Sie Prüfungen.",
    readTime: 6,
    difficulty: "beginner",
    tags: ["Arbeitsmittel", "Werkzeuge", "Wartung", "Prüfung"],
    views: 1120,
    helpful: 89,
    lastUpdated: "2026-02-05",
  },
  {
    id: "65",
    title: "Material: Inventar und Bestandsmanagement",
    description: "Verwalten Sie Verbrauchsmaterial, Mindestbestände und Bestellungen.",
    category: "Praxis & Einstellungen",
    categoryId: "praxis",
    content: "Unter /inventory verwalten Sie Ihren Materialbestand. Definieren Sie Mindestbestände und erhalten Sie automatische Bestellvorschläge. Tracken Sie Verbrauch und Kosten. Barcode-Scanning für schnelle Bestandsaufnahme.",
    readTime: 10,
    difficulty: "intermediate",
    tags: ["Material", "Inventar", "Bestand", "Bestellung", "Verbrauch"],
    views: 2120,
    helpful: 178,
    lastUpdated: "2026-02-10",
  },
  {
    id: "66",
    title: "Geräte: Medizingeräte und Wartung",
    description: "Verwalten Sie medizinische Geräte mit Wartungszyklen, Einweisungen und MPBetreibV-Konformität.",
    category: "Praxis & Einstellungen",
    categoryId: "praxis",
    content: "Unter /devices erfassen Sie alle Geräte mit Seriennummer, Wartungsintervallen und Fotos. Dokumentieren Sie Mitarbeiter-Einweisungen und Wartungsberichte. Automatische Erinnerungen an fällige Wartungen. Überfällige Wartungen fließen in die KI-Analyse ein.",
    readTime: 12,
    difficulty: "intermediate",
    tags: ["Geräte", "Wartung", "Einweisung", "MPBetreibV", "Medizinprodukte"],
    views: 2890,
    helpful: 245,
    lastUpdated: "2026-02-15",
  },
  {
    id: "67",
    title: "Einstellungen: Praxis und Profil konfigurieren",
    description: "Praxisinformationen, Benachrichtigungen, Darstellung und Sicherheitseinstellungen.",
    category: "Praxis & Einstellungen",
    categoryId: "praxis",
    content: "Unter /settings konfigurieren Sie: Praxisinformationen, Öffnungszeiten, Benachrichtigungspräferenzen, Farbschema und mehr. Unter /profile verwalten Sie Ihre persönlichen Daten und Passwort.",
    readTime: 8,
    difficulty: "beginner",
    tags: ["Einstellungen", "Profil", "Konfiguration", "Sicherheit"],
    views: 3450,
    helpful: 289,
    lastUpdated: "2026-02-12",
  },
]

// ─── VIDEO TUTORIALS ───
export const videoTutorials: VideoTutorial[] = [
  {
    id: "v1",
    title: "Effizienz Praxis Einführung: Von 0 auf 100",
    description: "Kompletter Rundgang: Dashboard, Team, Kalender, Workflows, Dokumente und KI-Analyse.",
    duration: "22:30",
    thumbnail: "/medical-practice-setup-tutorial.jpg",
    category: "Übersicht",
    categoryId: "overview",
    views: 15230,
    chapters: [
      { title: "Anmeldung & Dashboard konfigurieren", time: "0:00" },
      { title: "Praxis einrichten & Grunddaten", time: "3:00" },
      { title: "Team anlegen & Rollen zuweisen", time: "6:30" },
      { title: "Kalender, Dienstplan & Zeiterfassung", time: "10:00" },
      { title: "Aufgaben, Workflows & Zuständigkeiten", time: "13:30" },
      { title: "Dokumente, Protokolle & QM", time: "17:00" },
      { title: "KI-Analyse & Schwarzes Brett", time: "20:00" },
    ],
  },
  {
    id: "v2",
    title: "Team-Management: Mitarbeiter, Skills & Personalsuche",
    description: "Mitarbeiterverwaltung, Kompetenzmatrix, Organigramm, Fortbildung und Recruiting.",
    duration: "18:45",
    thumbnail: "/team-management-tutorial.jpg",
    category: "Team & Personal",
    categoryId: "team",
    views: 9820,
    chapters: [
      { title: "Mitarbeiter hinzufügen & Rollen", time: "0:00" },
      { title: "Kompetenzen & Skills-Matrix", time: "4:00" },
      { title: "Organigramm nutzen", time: "7:30" },
      { title: "Personalsuche & Kandidaten", time: "10:00" },
      { title: "Dienstplan & Zeiterfassung", time: "13:00" },
      { title: "Mitarbeitergespräche & Fortbildung", time: "16:00" },
    ],
  },
  {
    id: "v3",
    title: "Planung & Organisation: Workflows, Aufgaben & Ziele",
    description: "Workflows erstellen, Aufgaben delegieren, Zuständigkeiten definieren und Ziele verfolgen.",
    duration: "16:20",
    thumbnail: "/calendar-scheduling-tutorial.jpg",
    category: "Planung & Organisation",
    categoryId: "planning",
    views: 7450,
    chapters: [
      { title: "Workflow-Vorlagen erstellen", time: "0:00" },
      { title: "Checklisten & Schritte", time: "3:30" },
      { title: "Aufgaben & Todos verwalten", time: "7:00" },
      { title: "Zuständigkeiten definieren", time: "10:00" },
      { title: "Ziele setzen & KPIs verfolgen", time: "13:00" },
    ],
  },
  {
    id: "v4",
    title: "KI-Analyse & Strategietools",
    description: "KI-Praxisanalyse, Konkurrenz, IGeL, Leitbild, ROI und Strategieentwicklung.",
    duration: "24:15",
    thumbnail: "/ai-features-tutorial.png",
    category: "Strategie & Führung",
    categoryId: "strategy",
    views: 6340,
    chapters: [
      { title: "KI-Praxisanalyse starten", time: "0:00" },
      { title: "Praxis-Score verstehen", time: "3:00" },
      { title: "Konkurrenzanalyse", time: "7:00" },
      { title: "IGeL & ROI analysieren", time: "12:00" },
      { title: "Leitbild mit KI erstellen", time: "17:00" },
      { title: "Strategiepfad & Leadership", time: "20:00" },
    ],
  },
  {
    id: "v5",
    title: "Qualitätsmanagement: Hygiene, CIRS & Geräte",
    description: "QM-Handbuch, Hygienepläne, Verbesserungsmeldungen und Gerätemanagement.",
    duration: "14:00",
    thumbnail: "/medical-practice-setup-tutorial.jpg",
    category: "Qualitätsmanagement",
    categoryId: "quality",
    views: 4560,
    chapters: [
      { title: "QM-Handbuch / Wissen", time: "0:00" },
      { title: "Hygieneplan erstellen", time: "3:30" },
      { title: "CIRS: Meldungen erfassen", time: "6:30" },
      { title: "Geräte & Wartung", time: "9:00" },
      { title: "Einweisungen dokumentieren", time: "12:00" },
    ],
  },
  {
    id: "v6",
    title: "Wellbeing, Umfragen & Schwarzes Brett",
    description: "Team-Stimmung, Umfragen, interne Kommunikation und das Schwarze Brett nutzen.",
    duration: "12:30",
    thumbnail: "/team-management-tutorial.jpg",
    category: "Praxis & Einstellungen",
    categoryId: "praxis",
    views: 3890,
    chapters: [
      { title: "Schwarzes Brett Beiträge", time: "0:00" },
      { title: "Umfrage erstellen", time: "3:00" },
      { title: "Wellbeing-Dashboard", time: "6:00" },
      { title: "Stimmungsabfrage & Kudos", time: "9:00" },
    ],
  },
]

// ─── LEARNING PATHS ───
export const learningPaths: LearningPath[] = [
  {
    id: "lp1",
    title: "Einsteiger-Kurs: Effizienz Praxis Grundlagen",
    description: "Perfekt für neue Nutzer: Dashboard, Team, Kalender, Aufgaben und Schwarzes Brett.",
    icon: GraduationCap,
    color: "text-blue-500",
    gradient: "from-blue-500 to-cyan-500",
    difficulty: "beginner",
    estimatedTime: "2 Stunden",
    enrolledCount: 1456,
    progress: 0,
    modules: [
      { id: "m1", title: "Dashboard & Cockpit konfigurieren", type: "video", duration: "10 min", completed: false },
      { id: "m2", title: "Praxis einrichten & Grunddaten", type: "article", duration: "15 min", completed: false },
      { id: "m3", title: "Team anlegen & Rollen", type: "practice", duration: "10 min", completed: false },
      { id: "m4", title: "Kalender & Termine erstellen", type: "video", duration: "12 min", completed: false },
      { id: "m5", title: "Aufgaben & Schwarzes Brett", type: "practice", duration: "10 min", completed: false },
      { id: "m6", title: "Quiz: Erste Schritte", type: "quiz", duration: "5 min", completed: false },
    ],
  },
  {
    id: "lp2",
    title: "Praxismanager-Zertifikat",
    description: "Team-Management, Dienstplan, KPIs, Workflows, QM und Hygienemanagement.",
    icon: Target,
    color: "text-emerald-500",
    gradient: "from-emerald-500 to-teal-500",
    difficulty: "intermediate",
    estimatedTime: "5 Stunden",
    enrolledCount: 892,
    progress: 0,
    modules: [
      { id: "m1", title: "Rollen & Berechtigungen", type: "video", duration: "20 min", completed: false },
      { id: "m2", title: "Dienstplan & Zeiterfassung", type: "article", duration: "25 min", completed: false },
      { id: "m3", title: "Workflows & Checklisten", type: "practice", duration: "30 min", completed: false },
      { id: "m4", title: "Kennzahlen & KPIs", type: "video", duration: "20 min", completed: false },
      { id: "m5", title: "QM-Handbuch & Hygieneplan", type: "article", duration: "20 min", completed: false },
      { id: "m6", title: "CIRS & Verbesserungsmeldungen", type: "practice", duration: "15 min", completed: false },
      { id: "m7", title: "Mitarbeitergespräche führen", type: "practice", duration: "25 min", completed: false },
      { id: "m8", title: "Abschlussprüfung", type: "quiz", duration: "20 min", completed: false },
    ],
  },
  {
    id: "lp3",
    title: "KI & Strategie Power-User",
    description: "KI-Analyse, Konkurrenz, IGeL, Leitbild, Leadership und Strategieentwicklung.",
    icon: Brain,
    color: "text-indigo-500",
    gradient: "from-indigo-500 to-blue-500",
    difficulty: "advanced",
    estimatedTime: "3.5 Stunden",
    enrolledCount: 567,
    progress: 0,
    modules: [
      { id: "m1", title: "KI-Praxisanalyse & Praxis-Score", type: "video", duration: "15 min", completed: false },
      { id: "m2", title: "Journal & Handlungsempfehlungen", type: "article", duration: "10 min", completed: false },
      { id: "m3", title: "Konkurrenzanalyse durchführen", type: "practice", duration: "30 min", completed: false },
      { id: "m4", title: "IGeL & ROI-Analyse", type: "article", duration: "20 min", completed: false },
      { id: "m5", title: "Leitbild & Strategiepfad", type: "practice", duration: "30 min", completed: false },
      { id: "m6", title: "Leadership & Wunschpatient", type: "video", duration: "15 min", completed: false },
      { id: "m7", title: "KI-Experten Quiz", type: "quiz", duration: "15 min", completed: false },
    ],
  },
  {
    id: "lp4",
    title: "Wellbeing & Teamkultur",
    description: "Wellbeing, Umfragen, Kommunikation, Selbst-Check und Mitarbeiterentwicklung.",
    icon: Heart,
    color: "text-rose-500",
    gradient: "from-rose-500 to-pink-500",
    difficulty: "intermediate",
    estimatedTime: "2.5 Stunden",
    enrolledCount: 423,
    progress: 0,
    modules: [
      { id: "m1", title: "Wellbeing-Funktionen", type: "video", duration: "12 min", completed: false },
      { id: "m2", title: "Umfragen erstellen & auswerten", type: "practice", duration: "20 min", completed: false },
      { id: "m3", title: "Schwarzes Brett nutzen", type: "article", duration: "10 min", completed: false },
      { id: "m4", title: "Selbst-Check durchführen", type: "practice", duration: "15 min", completed: false },
      { id: "m5", title: "Mitarbeitergespräche vorbereiten", type: "practice", duration: "25 min", completed: false },
      { id: "m6", title: "Teamkultur-Quiz", type: "quiz", duration: "10 min", completed: false },
    ],
  },
]

// ─── FAQ ───
export const faqs: FAQ[] = [
  {
    id: "faq1",
    question: "Wie kann ich mein Passwort zurücksetzen?",
    answer: "Klicken Sie auf der Login-Seite auf 'Passwort vergessen'. Sie erhalten eine E-Mail mit einem Link zum Zurücksetzen. Alternativ können Sie unter Profil > Sicherheit Ihr Passwort jederzeit ändern.",
    category: "Account & Sicherheit",
    helpful: 312,
  },
  {
    id: "faq2",
    question: "Wie lade ich Mitarbeiter in meine Praxis ein?",
    answer: "Gehen Sie zu Team > Mitarbeiter hinzufügen. Geben Sie Name und E-Mail ein und wählen Sie eine Rolle (z.B. MFA, Arzt, Praxismanager). Der Mitarbeiter erhält eine Einladungs-E-Mail.",
    category: "Team & Personal",
    helpful: 278,
  },
  {
    id: "faq3",
    question: "Was kann die KI-Praxisanalyse für mich tun?",
    answer: "Die KI analysiert über 60 Datenpunkte (Team, Hygiene, CIRS, Fortbildung, Geräte, Finanzen) und berechnet einen Praxis-Score. Sie erhalten priorisierte Handlungsempfehlungen in den Kategorien Team, Finanzen, Hygiene, Sicherheit, Fortbildung und Kommunikation.",
    category: "Übersicht",
    helpful: 256,
  },
  {
    id: "faq4",
    question: "Wie erstelle ich einen Workflow oder eine Checkliste?",
    answer: "Unter Workflows > Neue Vorlage erstellen Sie Schritt-für-Schritt-Abläufe. Jeder Schritt kann Verantwortliche, Fristen und Checklisten-Punkte enthalten. Starten Sie Workflows manuell oder per Zeitplan.",
    category: "Planung & Organisation",
    helpful: 234,
  },
  {
    id: "faq5",
    question: "Wie funktioniert das Schwarze Brett?",
    answer: "Unter Schwarzes Brett erstellen Sie Beiträge mit Kategorie (aus Ihren Orga-Kategorien), Priorität und optionaler Lesebestätigung. Beiträge können angeheftet werden. Die Ansicht ist als Kachel- oder Listenansicht verfügbar.",
    category: "Übersicht",
    helpful: 223,
  },
  {
    id: "faq6",
    question: "Wie funktioniert das Gerätemanagement?",
    answer: "Unter Geräte erfassen Sie alle medizinischen Geräte mit Seriennummer, Wartungsintervall und Fotos. Das System erinnert an fällige Wartungen. Sie können Einweisungen pro Mitarbeiter dokumentieren.",
    category: "Praxis & Einstellungen",
    helpful: 212,
  },
  {
    id: "faq7",
    question: "Sind meine Daten DSGVO-konform gespeichert?",
    answer: "Ja, alle Daten werden DSGVO-konform auf europäischen Servern gespeichert. Modernste Verschlüsselung, volle Datenkontrolle, Export und Löschung jederzeit möglich.",
    category: "Account & Sicherheit",
    helpful: 289,
  },
  {
    id: "faq8",
    question: "Was ist CIRS und wie melde ich einen Vorfall?",
    answer: "CIRS (Critical Incident Reporting System) unter Verbesserungsmeldung ermöglicht anonyme Meldungen von Beinahe-Fehlern und Zwischenfällen. Offene Meldungen und deren Schweregrad fließen in den KI-Praxis-Score ein.",
    category: "Qualitätsmanagement",
    helpful: 198,
  },
  {
    id: "faq9",
    question: "Wie erstelle ich ein Praxis-Leitbild?",
    answer: "Unter Leitbild führt Sie ein geführter Prozess durch Vision, Mission und Werte. Die KI unterstützt bei der Formulierung. Das Leitbild können Sie im Team teilen und in die Strategieplanung einbinden.",
    category: "Strategie & Führung",
    helpful: 167,
  },
  {
    id: "faq10",
    question: "Kann ich Umfragen anonym durchführen?",
    answer: "Ja, beim Erstellen einer Umfrage aktivieren Sie die Option 'Anonym'. Ergebnisse werden ohne Zuordnung zu Teilnehmern gespeichert.",
    category: "Praxis & Einstellungen",
    helpful: 187,
  },
  {
    id: "faq11",
    question: "Wie funktioniert die Zeiterfassung?",
    answer: "Unter Zeiterfassung stempeln Mitarbeiter Beginn und Ende ihrer Arbeitszeit. Manager sehen eine Übersicht und können Korrekturen vornehmen. Unter Berichte erstellen Sie Auswertungen nach Zeitraum oder Mitarbeiter. Export als CSV/PDF.",
    category: "Planung & Organisation",
    helpful: 223,
  },
  {
    id: "faq12",
    question: "Wie konfiguriere ich mein Dashboard?",
    answer: "Klicken Sie im Dashboard auf das Zahnrad-Symbol. Im Dialog 'Cockpit bearbeiten' können Sie Widgets ein-/ausschalten, die Spaltenbreite pro Karte festlegen und per Drag & Drop umordnen. Trennlinien helfen bei der visuellen Gliederung.",
    category: "Übersicht",
    helpful: 245,
  },
  {
    id: "faq13",
    question: "Wie erstelle ich einen Hygieneplan?",
    answer: "Unter Hygieneplan erstellen Sie Reinigungspläne mit Intervallen und Verantwortlichen. Dokumentieren Sie Durchführungen und generieren Sie Compliance-Nachweise. Die Hygiene-Compliance-Rate fließt in die KI-Analyse ein.",
    category: "Qualitätsmanagement",
    helpful: 198,
  },
  {
    id: "faq14",
    question: "Wie funktioniert die Personalsuche?",
    answer: "Unter Personalsuche erstellen Sie Stellenanzeigen und verwalten Bewerbungen. Kandidaten durchlaufen Phasen (Neu/Kontaktiert/Interview/Angebot). Sie können VERAH- und NaPa-Qualifikationen kennzeichnen. Aktive Kandidaten erscheinen als Dashboard-Widget.",
    category: "Team & Personal",
    helpful: 178,
  },
]

// ─── SUGGESTED QUESTIONS ───
export const suggestedQuestions = [
  "Wie konfiguriere ich mein Dashboard?",
  "Wie lade ich Teammitglieder ein?",
  "Wie erstelle ich einen Workflow?",
  "Was zeigt die KI-Praxisanalyse?",
  "Wie funktioniert das Schwarze Brett?",
  "Wie nutze ich den Hygieneplan?",
  "Wie erstelle ich einen Dienstplan?",
  "Wie funktioniert die Personalsuche?",
  "Wie erstelle ich eine Umfrage?",
  "Wie melde ich einen CIRS-Vorfall?",
]

// ─── QUICK ACTIONS ── deep links into the app ───
export const quickActions = [
  { label: "Team verwalten", icon: Users, href: "/team", color: "text-teal-600" },
  { label: "Termin erstellen", icon: Calendar, href: "/calendar", color: "text-amber-600" },
  { label: "Aufgabe anlegen", icon: ClipboardList, href: "/todos", color: "text-blue-600" },
  { label: "Workflow erstellen", icon: Workflow, href: "/workflows", color: "text-indigo-600" },
  { label: "KI-Analyse", icon: BarChart3, href: "/analysis", color: "text-emerald-600" },
  { label: "Schwarzes Brett", icon: Clipboard, href: "/schwarzes-brett", color: "text-rose-600" },
]
