import {
  Rocket,
  Users,
  Calendar,
  Workflow,
  FileText,
  BarChart3,
  Brain,
  Shield,
  UserPlus,
  Upload,
  GraduationCap,
  Target,
  Heart,
  MonitorCheck,
  MessageSquare,
  ClipboardList,
} from "lucide-react"
import type { HelpArticle, FAQ, VideoTutorial, LearningPath, HelpCategory } from "./types"

export const helpCategories: HelpCategory[] = [
  {
    id: "getting-started",
    name: "Erste Schritte",
    icon: Rocket,
    color: "text-blue-500",
    bgColor: "bg-blue-500/10",
    borderColor: "border-blue-500/20",
    gradient: "from-blue-500 to-cyan-500",
    description: "Praxis einrichten, Onboarding & Grundlagen",
    articleCount: 8,
  },
  {
    id: "team",
    name: "Team & Mitarbeiter",
    icon: Users,
    color: "text-emerald-500",
    bgColor: "bg-emerald-500/10",
    borderColor: "border-emerald-500/20",
    gradient: "from-emerald-500 to-teal-500",
    description: "Mitarbeiterverwaltung, Skills, Organigramm & Dienstplan",
    articleCount: 10,
  },
  {
    id: "calendar",
    name: "Kalender & Termine",
    icon: Calendar,
    color: "text-amber-500",
    bgColor: "bg-amber-500/10",
    borderColor: "border-amber-500/20",
    gradient: "from-amber-500 to-orange-500",
    description: "Terminplanung, Zeiterfassung & Dienstplan",
    articleCount: 6,
  },
  {
    id: "workflows",
    name: "Workflows & Aufgaben",
    icon: Workflow,
    color: "text-purple-500",
    bgColor: "bg-purple-500/10",
    borderColor: "border-purple-500/20",
    gradient: "from-purple-500 to-pink-500",
    description: "Checklisten, Aufgaben, Zuständigkeiten & Automatisierung",
    articleCount: 8,
  },
  {
    id: "documents",
    name: "Dokumente & Wissen",
    icon: FileText,
    color: "text-rose-500",
    bgColor: "bg-rose-500/10",
    borderColor: "border-rose-500/20",
    gradient: "from-rose-500 to-red-500",
    description: "QM-Handbuch, Protokolle, Wissensdatenbank & Hygiene",
    articleCount: 8,
  },
  {
    id: "analytics",
    name: "Analysen & Strategie",
    icon: BarChart3,
    color: "text-indigo-500",
    bgColor: "bg-indigo-500/10",
    borderColor: "border-indigo-500/20",
    gradient: "from-indigo-500 to-blue-500",
    description: "KPIs, Konkurrenzanalyse, IGeL/ROI & Strategiepfad",
    articleCount: 10,
  },
  {
    id: "ai",
    name: "KI-Funktionen",
    icon: Brain,
    color: "text-fuchsia-500",
    bgColor: "bg-fuchsia-500/10",
    borderColor: "border-fuchsia-500/20",
    gradient: "from-fuchsia-500 to-purple-500",
    description: "KI-Praxisanalyse, KI-Assistent & intelligente Vorschläge",
    articleCount: 6,
  },
  {
    id: "communication",
    name: "Kommunikation & Wellbeing",
    icon: MessageSquare,
    color: "text-teal-500",
    bgColor: "bg-teal-500/10",
    borderColor: "border-teal-500/20",
    gradient: "from-teal-500 to-emerald-500",
    description: "Nachrichten, Umfragen, Wellbeing & Mitarbeitergespräche",
    articleCount: 8,
  },
  {
    id: "resources",
    name: "Ressourcen & Inventar",
    icon: MonitorCheck,
    color: "text-orange-500",
    bgColor: "bg-orange-500/10",
    borderColor: "border-orange-500/20",
    gradient: "from-orange-500 to-amber-500",
    description: "Geräte, Räume, Arbeitsplätze & Materialverwaltung",
    articleCount: 6,
  },
  {
    id: "settings",
    name: "Einstellungen & Sicherheit",
    icon: Shield,
    color: "text-slate-500",
    bgColor: "bg-slate-500/10",
    borderColor: "border-slate-500/20",
    gradient: "from-slate-500 to-gray-500",
    description: "Profil, Praxiseinstellungen, Sicherheit & Datenschutz",
    articleCount: 6,
  },
]

export const helpArticles: HelpArticle[] = [
  // Erste Schritte
  {
    id: "1",
    title: "Schnellstart: Ihre Praxis in Effizienz Praxis einrichten",
    description:
      "Lernen Sie in wenigen Minuten, wie Sie Ihre Praxis anlegen, Mitarbeiter einladen und das Dashboard konfigurieren.",
    category: "Erste Schritte",
    categoryId: "getting-started",
    content:
      "Schritt 1: Loggen Sie sich ein und folgen Sie dem Onboarding-Wizard. Schritt 2: Geben Sie Ihre Praxisinformationen ein (Name, Adresse, Fachrichtung). Schritt 3: Laden Sie Teammitglieder per E-Mail ein. Schritt 4: Konfigurieren Sie Ihr Dashboard mit den für Sie relevanten Widgets. Schritt 5: Beginnen Sie mit der KI-Praxisanalyse, um sofortige Optimierungsvorschläge zu erhalten.",
    readTime: 8,
    difficulty: "beginner",
    tags: ["Einrichtung", "Onboarding", "Grundlagen", "Praxis"],
    views: 5210,
    helpful: 412,
    lastUpdated: "2026-02-01",
    author: "Effizienz Praxis Team",
  },
  {
    id: "2",
    title: "Das Dashboard verstehen und individuell gestalten",
    description:
      "Ihr Dashboard zeigt die wichtigsten KPIs, Aufgaben und Benachrichtigungen auf einen Blick. Erfahren Sie, wie Sie es anpassen.",
    category: "Erste Schritte",
    categoryId: "getting-started",
    content:
      "Das Dashboard unter /dashboard ist Ihre zentrale Anlaufstelle. Sie können Widgets per Drag & Drop umordnen, KPI-Kacheln hinzufügen/entfernen und zwischen verschiedenen Ansichten wechseln. Nutzen Sie die Analytics-Funktion unter /analytics für tiefere Einblicke.",
    readTime: 6,
    difficulty: "beginner",
    tags: ["Dashboard", "Widgets", "KPIs", "Anpassung"],
    views: 3890,
    helpful: 298,
    lastUpdated: "2026-01-28",
    author: "Effizienz Praxis Team",
  },
  // Team & Mitarbeiter
  {
    id: "3",
    title: "Mitarbeiter einladen und Rollen zuweisen",
    description:
      "So fügen Sie Teammitglieder hinzu, weisen Rollen zu und verwalten Zugriffsrechte in Ihrer Praxis.",
    category: "Team & Mitarbeiter",
    categoryId: "team",
    content:
      "Gehen Sie zu /team und klicken Sie auf 'Mitarbeiter hinzufügen'. Geben Sie E-Mail-Adresse und Rolle ein. Verfügbare Rollen: Praxisinhaber, Arzt, Praxismanager, MFA, Auszubildende. Jede Rolle hat vordefinierte Berechtigungen, die Sie unter Einstellungen anpassen können.",
    readTime: 7,
    difficulty: "beginner",
    tags: ["Team", "Mitarbeiter", "Rollen", "Berechtigungen", "Einladung"],
    views: 4120,
    helpful: 356,
    lastUpdated: "2026-02-05",
    author: "Effizienz Praxis Team",
  },
  {
    id: "4",
    title: "Skills-Management: Kompetenzen im Team verfolgen",
    description:
      "Erfassen und verwalten Sie Qualifikationen, Zertifizierungen und Fortbildungen Ihrer Mitarbeiter.",
    category: "Team & Mitarbeiter",
    categoryId: "team",
    content:
      "Unter /skills können Sie Kompetenzkategorien anlegen und jedem Mitarbeiter Fähigkeiten zuweisen. Das System erinnert automatisch an ablaufende Zertifikate und empfiehlt passende Fortbildungen aus der Academy (/academy).",
    readTime: 10,
    difficulty: "intermediate",
    tags: ["Skills", "Kompetenzen", "Fortbildung", "Zertifikate"],
    views: 2340,
    helpful: 187,
    lastUpdated: "2026-01-20",
  },
  {
    id: "5",
    title: "Organigramm erstellen und pflegen",
    description:
      "Visualisieren Sie die Struktur Ihrer Praxis mit dem interaktiven Organigramm.",
    category: "Team & Mitarbeiter",
    categoryId: "team",
    content:
      "Unter /organigramm wird automatisch eine visuelle Darstellung Ihrer Teamstruktur generiert. Sie können Hierarchien, Abteilungen und Verantwortlichkeiten per Drag & Drop anpassen. Das Organigramm lässt sich auch als PDF exportieren.",
    readTime: 5,
    difficulty: "beginner",
    tags: ["Organigramm", "Teamstruktur", "Organisation"],
    views: 1890,
    helpful: 156,
    lastUpdated: "2026-01-15",
  },
  {
    id: "6",
    title: "Mitarbeitergespräche planen und dokumentieren",
    description:
      "Strukturierte Gesprächsvorlagen, Zielverfolgung und automatische Erinnerungen für regelmäßige Feedbackgespräche.",
    category: "Team & Mitarbeiter",
    categoryId: "team",
    content:
      "Unter /mitarbeitergespraeche erstellen Sie Gesprächsvorlagen mit Bewertungskriterien. Planen Sie Jahres-, Halbjahres- oder Quartalsgespräche. Die KI schlägt geeignete Gesprächspunkte basierend auf aktuellen Zielen und Performance-Daten vor.",
    readTime: 12,
    difficulty: "intermediate",
    tags: ["Mitarbeitergespräche", "Feedback", "Ziele", "Performance"],
    views: 2670,
    helpful: 234,
    lastUpdated: "2026-02-03",
  },
  // Kalender & Termine
  {
    id: "7",
    title: "Kalender und Terminplanung effizient nutzen",
    description:
      "Termine erstellen, Ressourcen planen und den Team-Kalender verwalten.",
    category: "Kalender & Termine",
    categoryId: "calendar",
    content:
      "Der Kalender unter /calendar bietet Tages-, Wochen- und Monatsansicht. Erstellen Sie Termine per Klick, weisen Sie Räume und Mitarbeiter zu. Wiederkehrende Termine werden automatisch angelegt. Nutzen Sie Farbcodes für verschiedene Terminarten.",
    readTime: 10,
    difficulty: "beginner",
    tags: ["Kalender", "Termine", "Planung", "Ressourcen"],
    views: 3450,
    helpful: 278,
    lastUpdated: "2026-01-25",
  },
  {
    id: "8",
    title: "Zeiterfassung und Arbeitszeitberichte",
    description:
      "Erfassen Sie Arbeitszeiten, erstellen Sie Berichte und exportieren Sie Daten für die Lohnabrechnung.",
    category: "Kalender & Termine",
    categoryId: "calendar",
    content:
      "Unter /zeiterfassung können Mitarbeiter ihre Arbeitszeiten stempeln. Manager sehen eine Übersicht aller Zeiten. Unter /zeiterfassung/reports erstellen Sie detaillierte Berichte nach Zeitraum, Mitarbeiter oder Abteilung. Export als CSV/PDF ist möglich.",
    readTime: 8,
    difficulty: "intermediate",
    tags: ["Zeiterfassung", "Arbeitszeit", "Berichte", "Export"],
    views: 2890,
    helpful: 234,
    lastUpdated: "2026-02-01",
  },
  {
    id: "9",
    title: "Dienstplan erstellen und verwalten",
    description:
      "Schichtplanung, Urlaubsverwaltung und automatische Dienstplanvorschläge für Ihr Team.",
    category: "Kalender & Termine",
    categoryId: "calendar",
    content:
      "Unter /dienstplan erstellen Sie Schichtpläne per Drag & Drop. Das System berücksichtigt Arbeitsverträge, Urlaubsanträge und Qualifikationen. Die KI schlägt optimale Besetzungen vor und warnt bei Unterbesetzung.",
    readTime: 12,
    difficulty: "intermediate",
    tags: ["Dienstplan", "Schichtplanung", "Urlaub", "Besetzung"],
    views: 3120,
    helpful: 267,
    lastUpdated: "2026-01-30",
  },
  // Workflows & Aufgaben
  {
    id: "10",
    title: "Workflows und Checklisten erstellen",
    description:
      "Standardisieren Sie Praxisabläufe mit wiederverwendbaren Workflow-Vorlagen und Checklisten.",
    category: "Workflows & Aufgaben",
    categoryId: "workflows",
    content:
      "Unter /workflows erstellen Sie Vorlagen für wiederkehrende Prozesse wie Praxisöffnung, Gerätewartung oder Patientenaufnahme. Jeder Workflow besteht aus Schritten mit Zuweisungen, Fristen und Checklisten. Starten Sie Workflows manuell oder automatisch per Zeitplan.",
    readTime: 15,
    difficulty: "intermediate",
    tags: ["Workflows", "Checklisten", "Automatisierung", "Prozesse"],
    views: 2560,
    helpful: 212,
    lastUpdated: "2026-02-04",
  },
  {
    id: "11",
    title: "Aufgaben verwalten und delegieren",
    description:
      "Erstellen, zuweisen und verfolgen Sie Aufgaben im Team mit Prioritäten und Fristen.",
    category: "Workflows & Aufgaben",
    categoryId: "workflows",
    content:
      "Unter /todos verwalten Sie Ihre persönlichen Aufgaben. Als Manager können Sie Aufgaben an Teammitglieder delegieren. Setzen Sie Prioritäten (hoch/mittel/niedrig), Fälligkeitsdaten und verknüpfen Sie Aufgaben mit Workflows. Das Dashboard zeigt offene Aufgaben auf einen Blick.",
    readTime: 8,
    difficulty: "beginner",
    tags: ["Aufgaben", "Todos", "Delegation", "Prioritäten"],
    views: 3780,
    helpful: 312,
    lastUpdated: "2026-01-22",
  },
  {
    id: "12",
    title: "Zuständigkeiten und Verantwortlichkeiten definieren",
    description:
      "Klare Zuordnung von Verantwortungsbereichen für transparente Abläufe in der Praxis.",
    category: "Workflows & Aufgaben",
    categoryId: "workflows",
    content:
      "Unter /responsibilities definieren Sie, wer für welche Bereiche (z.B. Hygiene, Geräte, Labor) verantwortlich ist. Das System verknüpft Zuständigkeiten automatisch mit relevanten Workflows und Aufgaben.",
    readTime: 7,
    difficulty: "beginner",
    tags: ["Zuständigkeiten", "Verantwortung", "Organisation"],
    views: 1890,
    helpful: 156,
    lastUpdated: "2026-01-18",
  },
  {
    id: "13",
    title: "Ziele setzen und Fortschritt verfolgen",
    description:
      "Definieren Sie Team- und Praxisziele mit messbaren KPIs und verfolgen Sie den Fortschritt visuell.",
    category: "Workflows & Aufgaben",
    categoryId: "workflows",
    content:
      "Unter /goals erstellen Sie Ziele mit Beschreibung, Zielwert und Frist. Verknüpfen Sie Ziele mit KPIs aus der Praxisauswertung. Das Dashboard zeigt den Fortschritt aller aktiven Ziele. Mitarbeiter können eigene Teilziele erstellen.",
    readTime: 10,
    difficulty: "intermediate",
    tags: ["Ziele", "KPIs", "Fortschritt", "Performance"],
    views: 2340,
    helpful: 198,
    lastUpdated: "2026-02-02",
  },
  // Dokumente & Wissen
  {
    id: "14",
    title: "Dokumentenverwaltung und QM-Handbuch",
    description:
      "Verwalten Sie alle Praxisdokumente zentral mit Versionierung, Freigabeworkflows und digitalen Signaturen.",
    category: "Dokumente & Wissen",
    categoryId: "documents",
    content:
      "Unter /documents laden Sie Dokumente hoch und organisieren sie in Ordnern. Nutzen Sie Tags und Suchfunktionen. Das QM-Handbuch unter /knowledge enthält Ihre Standard Operating Procedures (SOPs). Dokumente können als Vorlagen für das ganze Team bereitgestellt werden.",
    readTime: 10,
    difficulty: "intermediate",
    tags: ["Dokumente", "QM-Handbuch", "Versionierung", "SOPs"],
    views: 2890,
    helpful: 245,
    lastUpdated: "2026-01-28",
  },
  {
    id: "15",
    title: "Gesprächsprotokolle erstellen und verwalten",
    description:
      "Dokumentieren Sie Teamsitzungen, Besprechungen und Patientengespräche mit strukturierten Protokollen.",
    category: "Dokumente & Wissen",
    categoryId: "documents",
    content:
      "Unter /protocols erstellen Sie neue Protokolle mit Vorlage, Teilnehmern und Tagesordnungspunkten. Die KI kann Protokolle automatisch aus Notizen generieren. Protokolle werden archiviert und sind durchsuchbar.",
    readTime: 8,
    difficulty: "beginner",
    tags: ["Protokolle", "Besprechung", "Dokumentation"],
    views: 2450,
    helpful: 198,
    lastUpdated: "2026-01-25",
  },
  {
    id: "16",
    title: "Hygieneplan und Hygienemanagement",
    description:
      "Erstellen und verwalten Sie Hygienepläne, Begehungsprotokolle und Reinigungsnachweise digital.",
    category: "Dokumente & Wissen",
    categoryId: "documents",
    content:
      "Unter /hygiene und /hygieneplan verwalten Sie alle hygienerelevanten Dokumente. Erstellen Sie Reinigungspläne, dokumentieren Sie Begehungen und generieren Sie Nachweise. Das System erinnert an fällige Kontrollen.",
    readTime: 10,
    difficulty: "intermediate",
    tags: ["Hygiene", "Hygieneplan", "QM", "Reinigung", "Begehung"],
    views: 3210,
    helpful: 267,
    lastUpdated: "2026-02-05",
  },
  // Analysen & Strategie
  {
    id: "17",
    title: "Praxisauswertung: KPIs und Kennzahlen verstehen",
    description:
      "Nutzen Sie die umfassende Auswertung mit anpassbaren Diagrammen und Benchmarks.",
    category: "Analysen & Strategie",
    categoryId: "analytics",
    content:
      "Unter /analytics sehen Sie Ihre wichtigsten Kennzahlen. Die Praxisauswertung zeigt Trends, Vergleiche und Prognosen. Passen Sie Dashboards individuell an, erstellen Sie benutzerdefinierte Diagramme und exportieren Sie Berichte als PDF.",
    readTime: 12,
    difficulty: "intermediate",
    tags: ["Auswertung", "KPIs", "Analytics", "Benchmarks", "Berichte"],
    views: 3450,
    helpful: 289,
    lastUpdated: "2026-02-03",
  },
  {
    id: "18",
    title: "Konkurrenzanalyse durchführen",
    description:
      "Vergleichen Sie Ihre Praxis mit Mitbewerbern in Ihrer Region und identifizieren Sie Differenzierungspotenziale.",
    category: "Analysen & Strategie",
    categoryId: "analytics",
    content:
      "Unter /competitor-analysis erstellen Sie eine neue Analyse. Die KI sammelt öffentlich verfügbare Daten zu Mitbewerbern: Leistungsspektrum, Google-Bewertungen, Online-Präsenz. Sie erhalten eine SWOT-Analyse und konkrete Handlungsempfehlungen.",
    readTime: 15,
    difficulty: "advanced",
    tags: ["Konkurrenz", "SWOT", "Wettbewerb", "Strategie"],
    views: 2120,
    helpful: 178,
    lastUpdated: "2026-01-30",
  },
  {
    id: "19",
    title: "IGeL-Analyse und ROI-Berechnung",
    description:
      "Bewerten Sie die Wirtschaftlichkeit individueller Gesundheitsleistungen mit der KI-gestützten Analyse.",
    category: "Analysen & Strategie",
    categoryId: "analytics",
    content:
      "Unter /igel und /roi-analysis analysieren Sie das Potenzial von IGeL-Leistungen. Die KI berechnet ROI, Marktpotenzial und gibt Empfehlungen zu Preisgestaltung und Marketing. Vergleichen Sie verschiedene Leistungen und priorisieren Sie nach Profitabilität.",
    readTime: 12,
    difficulty: "advanced",
    tags: ["IGeL", "ROI", "Wirtschaftlichkeit", "Selbstzahler"],
    views: 1890,
    helpful: 167,
    lastUpdated: "2026-01-28",
  },
  {
    id: "20",
    title: "Strategiepfad und Leitbild entwickeln",
    description:
      "Definieren Sie Vision, Mission und strategische Ziele Ihrer Praxis systematisch.",
    category: "Analysen & Strategie",
    categoryId: "analytics",
    content:
      "Unter /strategy-journey durchlaufen Sie einen geführten Prozess zur Strategieentwicklung. Unter /leitbild erstellen Sie Ihr Praxis-Leitbild mit KI-Unterstützung. Die Ergebnisse fließen in Ihre Zielsetzung und KPI-Planung ein.",
    readTime: 15,
    difficulty: "advanced",
    tags: ["Strategie", "Leitbild", "Vision", "Mission", "Planung"],
    views: 1560,
    helpful: 134,
    lastUpdated: "2026-01-20",
  },
  {
    id: "21",
    title: "Wunschpatient-Profil erstellen",
    description:
      "Definieren Sie Ihr ideales Patientenprofil und richten Sie Marketing und Leistungen gezielt darauf aus.",
    category: "Analysen & Strategie",
    categoryId: "analytics",
    content:
      "Unter /wunschpatient erstellen Sie detaillierte Profile Ihrer Zielgruppe. Die KI analysiert Ihre Patientenstruktur und gibt Empfehlungen zur optimalen Positionierung. Verknüpfen Sie Wunschpatienten-Profile mit Ihrer Marketing-Strategie.",
    readTime: 10,
    difficulty: "intermediate",
    tags: ["Wunschpatient", "Zielgruppe", "Marketing", "Positionierung"],
    views: 1780,
    helpful: 145,
    lastUpdated: "2026-01-22",
  },
  // KI-Funktionen
  {
    id: "22",
    title: "KI-Praxisanalyse: Stärken und Schwächen erkennen",
    description:
      "Die KI analysiert Ihre Praxisdaten automatisch und identifiziert Optimierungspotenziale.",
    category: "KI-Funktionen",
    categoryId: "ai",
    content:
      "Unter /practice-insights führt die KI eine umfassende Analyse durch: Auslastung, Patientenstruktur, Finanzen, Teamperformance. Sie erhalten eine priorisierte Liste von Verbesserungsvorschlägen mit geschätztem Aufwand und Nutzen. Die Analyse wird wöchentlich automatisch aktualisiert.",
    readTime: 10,
    difficulty: "beginner",
    tags: ["KI", "Analyse", "Optimierung", "SWOT", "Empfehlungen"],
    views: 4560,
    helpful: 378,
    lastUpdated: "2026-02-06",
  },
  {
    id: "23",
    title: "KI-Assistent im Hilfe-Center",
    description:
      "Stellen Sie Fragen in natürlicher Sprache und erhalten Sie sofort personalisierte Antworten.",
    category: "KI-Funktionen",
    categoryId: "ai",
    content:
      "Im Tab 'KI-Assistent' dieses Hilfe-Centers können Sie Fragen zu jeder Funktion stellen. Die KI kennt Ihre Praxiskonfiguration und gibt kontextbezogene Antworten. Sie können z.B. fragen: 'Wie erstelle ich einen Dienstplan?' oder 'Welche KPIs sollte ich beobachten?'",
    readTime: 5,
    difficulty: "beginner",
    tags: ["KI", "Assistent", "Chat", "Hilfe", "Support"],
    views: 3890,
    helpful: 334,
    lastUpdated: "2026-02-08",
  },
  {
    id: "24",
    title: "Effizienz-Check: Selbstbewertung Ihrer Praxis",
    description:
      "Führen Sie einen strukturierten Selbst-Check durch, um Verbesserungspotenziale zu identifizieren.",
    category: "KI-Funktionen",
    categoryId: "ai",
    content:
      "Unter /selbst-check beantworten Sie einen Fragebogen zu verschiedenen Praxisbereichen. Die KI wertet Ihre Antworten aus und erstellt einen detaillierten Bericht mit Handlungsempfehlungen. Vergleichen Sie Ihre Ergebnisse über die Zeit und messen Sie Ihren Fortschritt.",
    readTime: 8,
    difficulty: "beginner",
    tags: ["Selbst-Check", "Effizienz", "Bewertung", "Fragebogen"],
    views: 2340,
    helpful: 198,
    lastUpdated: "2026-01-25",
  },
  // Kommunikation & Wellbeing
  {
    id: "25",
    title: "Nachrichten und interne Kommunikation",
    description:
      "Kommunizieren Sie sicher mit Ihrem Team per Chat, Gruppennachrichten und Ankündigungen.",
    category: "Kommunikation & Wellbeing",
    categoryId: "communication",
    content:
      "Unter /messages finden Sie die interne Kommunikationsplattform. Senden Sie Direktnachrichten, erstellen Sie Gruppenchats für Abteilungen und verfassen Sie Ankündigungen für das gesamte Team. Nachrichten sind Ende-zu-Ende verschlüsselt.",
    readTime: 6,
    difficulty: "beginner",
    tags: ["Nachrichten", "Chat", "Kommunikation", "Team"],
    views: 3120,
    helpful: 256,
    lastUpdated: "2026-02-01",
  },
  {
    id: "26",
    title: "Mitarbeiter-Umfragen erstellen und auswerten",
    description:
      "Erstellen Sie anonyme Umfragen zu Zufriedenheit, Arbeitsklima und Verbesserungsvorschlägen.",
    category: "Kommunikation & Wellbeing",
    categoryId: "communication",
    content:
      "Unter /surveys erstellen Sie Umfragen mit verschiedenen Fragetypen (Single/Multi-Choice, Freitext, Skala). Teilen Sie Umfragen per Link oder QR-Code. Die Auswertung zeigt Ergebnisse in Echtzeit mit Diagrammen und Trends.",
    readTime: 10,
    difficulty: "intermediate",
    tags: ["Umfragen", "Feedback", "Zufriedenheit", "Auswertung"],
    views: 2670,
    helpful: 223,
    lastUpdated: "2026-02-03",
  },
  {
    id: "27",
    title: "Team-Wellbeing und Stimmungsbarometer",
    description:
      "Verfolgen Sie die Team-Stimmung, erkennen Sie Belastungsspitzen und stärken Sie das Teamklima.",
    category: "Kommunikation & Wellbeing",
    categoryId: "communication",
    content:
      "Unter /wellbeing sehen Mitarbeiter ihren persönlichen Wellbeing-Status. Manager erhalten anonymisierte Teamdaten. Funktionen: Stimmungsabfragen, Kudos/Lob, Arbeitsbelastungsanzeige und Verbesserungsvorschläge. Das System erkennt Trends und warnt bei kritischen Mustern.",
    readTime: 8,
    difficulty: "beginner",
    tags: ["Wellbeing", "Stimmung", "Teamklima", "Kudos", "Gesundheit"],
    views: 2450,
    helpful: 212,
    lastUpdated: "2026-02-05",
  },
  {
    id: "28",
    title: "Tickets erstellen und Support anfragen",
    description:
      "Bei technischen Problemen oder Wünschen erstellen Sie ein Support-Ticket direkt aus der Anwendung.",
    category: "Kommunikation & Wellbeing",
    categoryId: "communication",
    content:
      "Unter /tickets erstellen Sie Support-Anfragen mit Kategorie, Priorität und Beschreibung. Fügen Sie Screenshots hinzu. Das Support-Team antwortet direkt im Ticket. Sie sehen den Status jederzeit.",
    readTime: 5,
    difficulty: "beginner",
    tags: ["Tickets", "Support", "Hilfe", "Probleme"],
    views: 1890,
    helpful: 167,
    lastUpdated: "2026-01-20",
  },
  // Ressourcen & Inventar
  {
    id: "29",
    title: "Gerätemanagement: Wartung, Einweisungen & Übersicht",
    description:
      "Verwalten Sie medizinische Geräte mit Wartungszyklen, Mitarbeiter-Einweisungen und Dokumentation.",
    category: "Ressourcen & Inventar",
    categoryId: "resources",
    content:
      "Unter /devices erfassen Sie alle Geräte mit Seriennummer, Wartungsintervallen und Fotos. Dokumentieren Sie Mitarbeiter-Einweisungen und Wartungsberichte. Das System erinnert automatisch an fällige Wartungen und fehlende Einweisungen.",
    readTime: 12,
    difficulty: "intermediate",
    tags: ["Geräte", "Wartung", "Einweisung", "Medizinprodukte", "MPBetreibV"],
    views: 2890,
    helpful: 245,
    lastUpdated: "2026-02-06",
  },
  {
    id: "30",
    title: "Räume und Arbeitsplätze verwalten",
    description:
      "Erstellen Sie einen digitalen Raumplan und verwalten Sie Arbeitsplätze und deren Ausstattung.",
    category: "Ressourcen & Inventar",
    categoryId: "resources",
    content:
      "Unter /rooms verwalten Sie Ihre Praxisräume mit Ausstattung und Kapazität. Unter /arbeitsplaetze ordnen Sie Arbeitsplätze Räumen zu. Verknüpfen Sie Räume mit Terminen und Ressourcenplanung.",
    readTime: 7,
    difficulty: "beginner",
    tags: ["Räume", "Arbeitsplätze", "Raumplan", "Ausstattung"],
    views: 1560,
    helpful: 123,
    lastUpdated: "2026-01-18",
  },
  {
    id: "31",
    title: "Materialverwaltung und Inventar",
    description:
      "Behalten Sie den Überblick über Verbrauchsmaterialien, Bestellungen und Mindestbestände.",
    category: "Ressourcen & Inventar",
    categoryId: "resources",
    content:
      "Unter /inventory verwalten Sie Ihren Materialbestand. Definieren Sie Mindestbestände und erhalten Sie automatische Bestellvorschläge. Tracken Sie Verbrauch und Kosten. Das System unterstützt Barcode-Scanning für schnelle Bestandsaufnahme.",
    readTime: 10,
    difficulty: "intermediate",
    tags: ["Material", "Inventar", "Bestand", "Bestellung", "Verbrauch"],
    views: 2120,
    helpful: 178,
    lastUpdated: "2026-01-28",
  },
  // Einstellungen & Sicherheit
  {
    id: "32",
    title: "Praxis- und Profilseinstellungen anpassen",
    description:
      "Konfigurieren Sie Ihre persönlichen Einstellungen, Praxisdaten und Benachrichtigungen.",
    category: "Einstellungen & Sicherheit",
    categoryId: "settings",
    content:
      "Unter /settings finden Sie alle Einstellungen: Praxisinformationen, Öffnungszeiten, Benachrichtigungspräferenzen, Farbschema und mehr. Unter /profile verwalten Sie Ihre persönlichen Daten, Passwort und Zwei-Faktor-Authentifizierung.",
    readTime: 8,
    difficulty: "beginner",
    tags: ["Einstellungen", "Profil", "Konfiguration", "Benachrichtigungen"],
    views: 3450,
    helpful: 289,
    lastUpdated: "2026-02-01",
  },
  {
    id: "33",
    title: "CIRS: Fehlermanagement und Sicherheitsberichte",
    description:
      "Dokumentieren Sie kritische Zwischenfälle anonym und verbessern Sie die Patientensicherheit.",
    category: "Einstellungen & Sicherheit",
    categoryId: "settings",
    content:
      "Unter /cirs können Mitarbeiter Beinahe-Fehler und Zwischenfälle anonym melden. Das CIRS-System (Critical Incident Reporting System) ermöglicht anonyme Meldungen, systematische Auswertung und die Ableitung von Verbesserungsmaßnahmen.",
    readTime: 10,
    difficulty: "intermediate",
    tags: ["CIRS", "Fehlermanagement", "Sicherheit", "Meldung", "QM"],
    views: 1890,
    helpful: 167,
    lastUpdated: "2026-01-22",
  },
  // Academy
  {
    id: "34",
    title: "Academy: Online-Fortbildung für Ihr Team",
    description:
      "Nutzen Sie die integrierte Lernplattform mit Kursen, Quizzes und Zertifikaten für Ihr Team.",
    category: "Erste Schritte",
    categoryId: "getting-started",
    content:
      "Unter /academy finden Sie Fortbildungskurse zu Praxismanagement, QM, Hygiene und mehr. Weisen Sie Kurse an Mitarbeiter zu, verfolgen Sie den Lernfortschritt und drucken Sie Zertifikate. Neue Kurse werden regelmäßig hinzugefügt.",
    readTime: 8,
    difficulty: "beginner",
    tags: ["Academy", "Fortbildung", "Kurse", "Zertifikate", "Lernen"],
    views: 2890,
    helpful: 234,
    lastUpdated: "2026-02-04",
  },
  {
    id: "35",
    title: "Bewertungsmanagement: Google Reviews und mehr",
    description:
      "Überwachen und verwalten Sie Online-Bewertungen Ihrer Praxis zentral an einem Ort.",
    category: "Analysen & Strategie",
    categoryId: "analytics",
    content:
      "Das Bewertungsmanagement sammelt Online-Bewertungen von Google, Jameda und anderen Portalen. Erhalten Sie Benachrichtigungen bei neuen Bewertungen, antworten Sie direkt und analysieren Sie Trends in der Patientenzufriedenheit.",
    readTime: 8,
    difficulty: "intermediate",
    tags: ["Bewertungen", "Google Reviews", "Reputation", "Patientenzufriedenheit"],
    views: 2340,
    helpful: 198,
    lastUpdated: "2026-01-30",
  },
]

export const videoTutorials: VideoTutorial[] = [
  {
    id: "v1",
    title: "Effizienz Praxis Einführung: Von 0 auf 100",
    description:
      "Kompletter Rundgang durch alle Bereiche: Dashboard, Team, Kalender, Workflows, Dokumente und Analysen.",
    duration: "22:30",
    thumbnail: "/medical-practice-setup-tutorial.jpg",
    category: "Erste Schritte",
    categoryId: "getting-started",
    views: 15230,
    chapters: [
      { title: "Anmeldung & Dashboard", time: "0:00" },
      { title: "Praxis einrichten", time: "3:00" },
      { title: "Team anlegen & Rollen zuweisen", time: "6:30" },
      { title: "Kalender & Termine", time: "10:00" },
      { title: "Workflows & Aufgaben", time: "13:30" },
      { title: "Dokumente & QM", time: "17:00" },
      { title: "KI-Funktionen im Überblick", time: "20:00" },
    ],
  },
  {
    id: "v2",
    title: "Team-Management: Mitarbeiter, Skills & Dienstplan",
    description:
      "Alles über Mitarbeiterverwaltung, Kompetenzmatrix, Organigramm und Dienstplanung in Effizienz Praxis.",
    duration: "18:45",
    thumbnail: "/team-management-tutorial.jpg",
    category: "Team & Mitarbeiter",
    categoryId: "team",
    views: 9820,
    chapters: [
      { title: "Mitarbeiter hinzufügen", time: "0:00" },
      { title: "Rollen & Berechtigungen", time: "4:00" },
      { title: "Skills-Management", time: "7:30" },
      { title: "Organigramm nutzen", time: "10:00" },
      { title: "Dienstplan erstellen", time: "13:00" },
      { title: "Mitarbeitergespräche", time: "16:00" },
    ],
  },
  {
    id: "v3",
    title: "Workflows, Checklisten & Aufgaben automatisieren",
    description:
      "Standardisieren Sie Praxisabläufe: Von der Morgenroutine bis zur Gerätewartung.",
    duration: "16:20",
    thumbnail: "/calendar-scheduling-tutorial.jpg",
    category: "Workflows & Aufgaben",
    categoryId: "workflows",
    views: 7450,
    chapters: [
      { title: "Workflow-Vorlagen verstehen", time: "0:00" },
      { title: "Neue Vorlage erstellen", time: "3:30" },
      { title: "Checklisten hinzufügen", time: "7:00" },
      { title: "Aufgaben delegieren", time: "10:00" },
      { title: "Automatisierung einrichten", time: "13:00" },
    ],
  },
  {
    id: "v4",
    title: "KI-Praxisanalyse & Strategietools",
    description:
      "Nutzen Sie KI für Konkurrenzanalyse, IGeL-Bewertung, Leitbild-Erstellung und strategische Planung.",
    duration: "24:15",
    thumbnail: "/ai-features-tutorial.png",
    category: "KI-Funktionen",
    categoryId: "ai",
    views: 6340,
    chapters: [
      { title: "KI-Praxisanalyse starten", time: "0:00" },
      { title: "Konkurrenzanalyse durchführen", time: "5:00" },
      { title: "IGeL & ROI analysieren", time: "10:00" },
      { title: "Leitbild mit KI erstellen", time: "15:00" },
      { title: "Strategiepfad nutzen", time: "19:00" },
    ],
  },
  {
    id: "v5",
    title: "Gerätemanagement: Wartung, Einweisungen & MPBetreibV",
    description:
      "Geräte erfassen, Wartungszyklen verwalten, Einweisungen dokumentieren und gesetzliche Anforderungen erfüllen.",
    duration: "14:00",
    thumbnail: "/medical-practice-setup-tutorial.jpg",
    category: "Ressourcen & Inventar",
    categoryId: "resources",
    views: 4560,
    chapters: [
      { title: "Gerät anlegen", time: "0:00" },
      { title: "Bilder & Dokumente", time: "3:00" },
      { title: "Wartungsplan einrichten", time: "6:00" },
      { title: "Einweisungen dokumentieren", time: "9:00" },
      { title: "Wartungsbericht erstellen", time: "12:00" },
    ],
  },
  {
    id: "v6",
    title: "Wellbeing, Umfragen & Team-Kommunikation",
    description:
      "Team-Stimmung verfolgen, Umfragen durchführen und die interne Kommunikation verbessern.",
    duration: "12:30",
    thumbnail: "/team-management-tutorial.jpg",
    category: "Kommunikation & Wellbeing",
    categoryId: "communication",
    views: 3890,
    chapters: [
      { title: "Nachrichten senden", time: "0:00" },
      { title: "Umfrage erstellen", time: "3:00" },
      { title: "Wellbeing-Dashboard", time: "6:00" },
      { title: "Stimmungsabfrage & Kudos", time: "9:00" },
    ],
  },
]

export const learningPaths: LearningPath[] = [
  {
    id: "lp1",
    title: "Einsteiger-Kurs: Effizienz Praxis Grundlagen",
    description:
      "Perfekt für neue Nutzer: Lernen Sie Dashboard, Team-Management, Kalender und Aufgaben in strukturierten Lektionen.",
    icon: GraduationCap,
    color: "text-blue-500",
    gradient: "from-blue-500 to-cyan-500",
    difficulty: "beginner",
    estimatedTime: "2 Stunden",
    enrolledCount: 1456,
    progress: 0,
    modules: [
      { id: "m1", title: "Willkommen & Dashboard-Überblick", type: "video", duration: "10 min", completed: false },
      { id: "m2", title: "Praxis einrichten & Grunddaten", type: "article", duration: "15 min", completed: false },
      { id: "m3", title: "Quiz: Erste Schritte", type: "quiz", duration: "5 min", completed: false },
      { id: "m4", title: "Teammitglieder einladen", type: "practice", duration: "10 min", completed: false },
      { id: "m5", title: "Kalender & erste Termine", type: "video", duration: "12 min", completed: false },
      { id: "m6", title: "Aufgaben erstellen und zuweisen", type: "practice", duration: "10 min", completed: false },
    ],
  },
  {
    id: "lp2",
    title: "Praxismanager-Zertifikat",
    description:
      "Werden Sie Experte: Team-Management, Dienstplanung, KPIs, Workflows und Qualitätsmanagement.",
    icon: Target,
    color: "text-emerald-500",
    gradient: "from-emerald-500 to-teal-500",
    difficulty: "intermediate",
    estimatedTime: "5 Stunden",
    enrolledCount: 892,
    progress: 0,
    modules: [
      { id: "m1", title: "Rollen & Berechtigungen verwalten", type: "video", duration: "20 min", completed: false },
      { id: "m2", title: "Dienstplan & Zeiterfassung", type: "article", duration: "25 min", completed: false },
      { id: "m3", title: "Workflows & Checklisten erstellen", type: "practice", duration: "30 min", completed: false },
      { id: "m4", title: "KPIs verstehen und nutzen", type: "video", duration: "20 min", completed: false },
      { id: "m5", title: "QM-Handbuch & Hygiene", type: "article", duration: "20 min", completed: false },
      { id: "m6", title: "Mitarbeitergespräche führen", type: "practice", duration: "25 min", completed: false },
      { id: "m7", title: "Abschlussprüfung", type: "quiz", duration: "20 min", completed: false },
    ],
  },
  {
    id: "lp3",
    title: "KI & Strategie Power-User",
    description:
      "Maximieren Sie KI-Funktionen: Praxisanalyse, Konkurrenzanalyse, IGeL-Bewertung und Strategieentwicklung.",
    icon: Brain,
    color: "text-purple-500",
    gradient: "from-purple-500 to-pink-500",
    difficulty: "advanced",
    estimatedTime: "3.5 Stunden",
    enrolledCount: 567,
    progress: 0,
    modules: [
      { id: "m1", title: "KI-Praxisanalyse verstehen", type: "video", duration: "15 min", completed: false },
      { id: "m2", title: "Konkurrenzanalyse durchführen", type: "practice", duration: "30 min", completed: false },
      { id: "m3", title: "IGeL & ROI-Analyse", type: "article", duration: "20 min", completed: false },
      { id: "m4", title: "Leitbild & Strategie entwickeln", type: "practice", duration: "30 min", completed: false },
      { id: "m5", title: "Wunschpatient definieren", type: "video", duration: "15 min", completed: false },
      { id: "m6", title: "KI-Experten Quiz", type: "quiz", duration: "15 min", completed: false },
    ],
  },
  {
    id: "lp4",
    title: "Wellbeing & Teamkultur",
    description:
      "Stärken Sie die Teamkultur: Wellbeing-Programme, Umfragen, Kommunikation und Mitarbeiterentwicklung.",
    icon: Heart,
    color: "text-rose-500",
    gradient: "from-rose-500 to-pink-500",
    difficulty: "intermediate",
    estimatedTime: "2.5 Stunden",
    enrolledCount: 423,
    progress: 0,
    modules: [
      { id: "m1", title: "Wellbeing-Funktionen kennenlernen", type: "video", duration: "12 min", completed: false },
      { id: "m2", title: "Umfragen erstellen & auswerten", type: "practice", duration: "20 min", completed: false },
      { id: "m3", title: "Kommunikation im Team stärken", type: "article", duration: "15 min", completed: false },
      { id: "m4", title: "Mitarbeitergespräche vorbereiten", type: "practice", duration: "25 min", completed: false },
      { id: "m5", title: "Teamkultur-Quiz", type: "quiz", duration: "10 min", completed: false },
    ],
  },
]

export const faqs: FAQ[] = [
  {
    id: "faq1",
    question: "Wie kann ich mein Passwort zurücksetzen?",
    answer:
      "Klicken Sie auf der Login-Seite auf 'Passwort vergessen'. Sie erhalten eine E-Mail mit einem Link zum Zurücksetzen. Alternativ können Sie unter Profil > Sicherheit Ihr Passwort jederzeit ändern.",
    category: "Account & Sicherheit",
    helpful: 312,
  },
  {
    id: "faq2",
    question: "Wie lade ich Mitarbeiter in meine Praxis ein?",
    answer:
      "Gehen Sie zu Team > Mitarbeiter hinzufügen. Geben Sie Name und E-Mail ein und wählen Sie eine Rolle (z.B. MFA, Arzt, Praxismanager). Der Mitarbeiter erhält eine Einladungs-E-Mail und kann sich direkt registrieren.",
    category: "Team & Mitarbeiter",
    helpful: 278,
  },
  {
    id: "faq3",
    question: "Was kann die KI-Praxisanalyse für mich tun?",
    answer:
      "Die KI analysiert alle verfügbaren Praxisdaten (KPIs, Auslastung, Teamstruktur) und identifiziert Stärken, Schwächen und Verbesserungspotenziale. Sie erhalten priorisierte Handlungsempfehlungen mit geschätztem Aufwand und Nutzen.",
    category: "KI-Funktionen",
    helpful: 256,
  },
  {
    id: "faq4",
    question: "Wie erstelle ich einen Workflow oder eine Checkliste?",
    answer:
      "Unter Workflows > Neue Vorlage erstellen Sie Schritt-für-Schritt-Abläufe. Jeder Schritt kann Verantwortliche, Fristen und Checklisten-Punkte enthalten. Sie können aus bestehenden Vorlagen wählen oder eigene erstellen.",
    category: "Workflows & Aufgaben",
    helpful: 234,
  },
  {
    id: "faq5",
    question: "Wie funktioniert das Gerätemanagement?",
    answer:
      "Unter Geräte erfassen Sie alle medizinischen Geräte mit Seriennummer, Wartungsintervall und Fotos. Das System erinnert automatisch an fällige Wartungen. Sie können Einweisungen pro Mitarbeiter dokumentieren und Wartungsberichte erstellen.",
    category: "Ressourcen & Inventar",
    helpful: 212,
  },
  {
    id: "faq6",
    question: "Sind meine Daten DSGVO-konform gespeichert?",
    answer:
      "Ja, alle Daten werden DSGVO-konform auf europäischen Servern gespeichert. Wir setzen modernste Verschlüsselungstechnologie ein. Sie haben jederzeit die volle Kontrolle über Ihre Daten und können diese exportieren oder löschen.",
    category: "Datenschutz & Sicherheit",
    helpful: 289,
  },
  {
    id: "faq7",
    question: "Wie nutze ich die Konkurrenzanalyse?",
    answer:
      "Unter Konkurrenzanalyse erstellen Sie eine neue Analyse. Die KI sammelt öffentlich verfügbare Daten zu Mitbewerbern: Google-Bewertungen, Leistungsspektrum, Online-Präsenz. Sie erhalten eine SWOT-Analyse mit konkreten Empfehlungen zur Differenzierung.",
    category: "Analysen & Strategie",
    helpful: 198,
  },
  {
    id: "faq8",
    question: "Kann ich Umfragen anonym durchführen?",
    answer:
      "Ja, beim Erstellen einer Umfrage können Sie die Option 'Anonym' aktivieren. Ergebnisse werden dann ohne Zuordnung zu Teilnehmern gespeichert. Dies ist besonders für Mitarbeiterbefragungen und Wellbeing-Checks empfehlenswert.",
    category: "Kommunikation & Wellbeing",
    helpful: 187,
  },
  {
    id: "faq9",
    question: "Wie erstelle ich ein Praxis-Leitbild?",
    answer:
      "Unter Leitbild führt Sie ein geführter Prozess durch die Erstellung. Die KI unterstützt Sie bei der Formulierung von Vision, Mission und Werten. Sie können das Leitbild mit Ihrem Team teilen und in die Strategieplanung einbinden.",
    category: "Analysen & Strategie",
    helpful: 167,
  },
  {
    id: "faq10",
    question: "Was ist das CIRS-System?",
    answer:
      "CIRS (Critical Incident Reporting System) ermöglicht es Mitarbeitern, Beinahe-Fehler und kritische Zwischenfälle anonym zu melden. Dies hilft, Risiken frühzeitig zu erkennen und die Patientensicherheit kontinuierlich zu verbessern.",
    category: "Qualitätsmanagement",
    helpful: 156,
  },
  {
    id: "faq11",
    question: "Welche Berichte kann ich exportieren?",
    answer:
      "Fast alle Bereiche bieten Export-Funktionen: KPI-Berichte als PDF/CSV, Zeiterfassung für die Lohnabrechnung, Protokolle, Hygienepläne und Gerätedokumentation. Gehen Sie in den jeweiligen Bereich und klicken Sie auf das Export-Symbol.",
    category: "Allgemein",
    helpful: 234,
  },
  {
    id: "faq12",
    question: "Wie funktioniert die Zeiterfassung?",
    answer:
      "Unter Zeiterfassung stempeln Mitarbeiter Beginn und Ende ihrer Arbeitszeit. Manager sehen eine Übersicht aller Zeiten und können Korrekturen vornehmen. Unter Zeiterfassung > Berichte erstellen Sie Auswertungen nach Zeitraum oder Mitarbeiter.",
    category: "Kalender & Termine",
    helpful: 223,
  },
]

export const suggestedQuestions = [
  "Wie richte ich meine Praxis ein?",
  "Wie lade ich Teammitglieder ein?",
  "Wie erstelle ich einen Workflow?",
  "Was kann die KI-Praxisanalyse?",
  "Wie funktioniert das Gerätemanagement?",
  "Wie erstelle ich eine Mitarbeiterumfrage?",
  "Wie nutze ich die Konkurrenzanalyse?",
  "Wie erstelle ich einen Dienstplan?",
]

export const quickActions = [
  { label: "Mitarbeiter einladen", icon: UserPlus, href: "/team/add", color: "text-emerald-500" },
  { label: "Termin erstellen", icon: Calendar, href: "/calendar", color: "text-amber-500" },
  { label: "Aufgabe anlegen", icon: ClipboardList, href: "/todos", color: "text-blue-500" },
  { label: "Workflow erstellen", icon: Workflow, href: "/workflows", color: "text-purple-500" },
  { label: "Dokument hochladen", icon: Upload, href: "/documents", color: "text-rose-500" },
  { label: "KI-Analyse starten", icon: Brain, href: "/practice-insights", color: "text-fuchsia-500" },
]
