import {
  Rocket,
  Users,
  Calendar,
  Workflow,
  FileText,
  BarChart3,
  Brain,
  Shield,
  UserPlus,
  Upload,
  GraduationCap,
} from "lucide-react"
import type { HelpArticle, FAQ, VideoTutorial, LearningPath, HelpCategory } from "./types"

export const helpCategories: HelpCategory[] = [
  {
    id: "getting-started",
    name: "Erste Schritte",
    icon: Rocket,
    color: "text-blue-500",
    bgColor: "bg-blue-500/10",
    borderColor: "border-blue-500/20",
    gradient: "from-blue-500 to-cyan-500",
    description: "Grundlagen und schneller Einstieg",
    articleCount: 12,
  },
  {
    id: "team",
    name: "Team & Mitarbeiter",
    icon: Users,
    color: "text-emerald-500",
    bgColor: "bg-emerald-500/10",
    borderColor: "border-emerald-500/20",
    gradient: "from-emerald-500 to-teal-500",
    description: "Mitarbeiterverwaltung & Rollen",
    articleCount: 18,
  },
  {
    id: "calendar",
    name: "Kalender & Termine",
    icon: Calendar,
    color: "text-amber-500",
    bgColor: "bg-amber-500/10",
    borderColor: "border-amber-500/20",
    gradient: "from-amber-500 to-orange-500",
    description: "Terminplanung & Ressourcen",
    articleCount: 15,
  },
  {
    id: "workflows",
    name: "Workflows & Aufgaben",
    icon: Workflow,
    color: "text-purple-500",
    bgColor: "bg-purple-500/10",
    borderColor: "border-purple-500/20",
    gradient: "from-purple-500 to-pink-500",
    description: "Automatisierung & Prozesse",
    articleCount: 22,
  },
  {
    id: "documents",
    name: "Dokumente & Vorlagen",
    icon: FileText,
    color: "text-rose-500",
    bgColor: "bg-rose-500/10",
    borderColor: "border-rose-500/20",
    gradient: "from-rose-500 to-red-500",
    description: "Dokumentenverwaltung & Signaturen",
    articleCount: 14,
  },
  {
    id: "analytics",
    name: "Analysen & Berichte",
    icon: BarChart3,
    color: "text-indigo-500",
    bgColor: "bg-indigo-500/10",
    borderColor: "border-indigo-500/20",
    gradient: "from-indigo-500 to-violet-500",
    description: "KPIs & Auswertungen",
    articleCount: 10,
  },
  {
    id: "ai",
    name: "KI-Funktionen",
    icon: Brain,
    color: "text-fuchsia-500",
    bgColor: "bg-fuchsia-500/10",
    borderColor: "border-fuchsia-500/20",
    gradient: "from-fuchsia-500 to-purple-500",
    description: "Intelligente Assistenz",
    articleCount: 8,
  },
  {
    id: "settings",
    name: "Einstellungen & Sicherheit",
    icon: Shield,
    color: "text-slate-500",
    bgColor: "bg-slate-500/10",
    borderColor: "border-slate-500/20",
    gradient: "from-slate-500 to-gray-500",
    description: "Konfiguration & Datenschutz",
    articleCount: 16,
  },
]

export const helpArticles: HelpArticle[] = [
  {
    id: "1",
    title: "Schnellstart: Ihre erste Praxis einrichten",
    description:
      "Lernen Sie in 10 Minuten die wichtigsten Grundlagen zur Einrichtung Ihrer Praxis in Effizienz Praxis.",
    category: "Erste Schritte",
    categoryId: "getting-started",
    content: "Vollständiger Artikel-Inhalt hier...",
    readTime: 10,
    difficulty: "beginner",
    tags: ["Einrichtung", "Grundlagen", "Start"],
    views: 4521,
    helpful: 342,
    lastUpdated: "2025-01-15",
    author: "Effizienz Team",
  },
  {
    id: "2",
    title: "Mitarbeiter einladen und Rollen zuweisen",
    description: "So fügen Sie Teammitglieder hinzu und konfigurieren deren Zugriffsrechte.",
    category: "Team & Mitarbeiter",
    categoryId: "team",
    content: "Vollständiger Artikel-Inhalt hier...",
    readTime: 8,
    difficulty: "beginner",
    tags: ["Team", "Einladung", "Rollen", "Berechtigungen"],
    views: 3892,
    helpful: 289,
    lastUpdated: "2025-01-12",
  },
  {
    id: "3",
    title: "Kalender optimal nutzen: Tipps & Tricks",
    description: "Fortgeschrittene Techniken zur effizienten Terminplanung und Ressourcenverwaltung.",
    category: "Kalender & Termine",
    categoryId: "calendar",
    content: "Vollständiger Artikel-Inhalt hier...",
    readTime: 15,
    difficulty: "intermediate",
    tags: ["Kalender", "Termine", "Ressourcen", "Planung"],
    views: 2845,
    helpful: 198,
    lastUpdated: "2025-01-10",
  },
  {
    id: "4",
    title: "Workflow-Automatisierung für Fortgeschrittene",
    description: "Erstellen Sie komplexe automatisierte Abläufe für wiederkehrende Praxisprozesse.",
    category: "Workflows & Aufgaben",
    categoryId: "workflows",
    content: "Vollständiger Artikel-Inhalt hier...",
    readTime: 20,
    difficulty: "advanced",
    tags: ["Workflow", "Automatisierung", "Prozesse"],
    views: 1923,
    helpful: 156,
    lastUpdated: "2025-01-08",
  },
  {
    id: "5",
    title: "KI-gestützte Dokumentenanalyse",
    description: "Nutzen Sie die KI um Dokumente automatisch zu analysieren und zusammenzufassen.",
    category: "KI-Funktionen",
    categoryId: "ai",
    content: "Vollständiger Artikel-Inhalt hier...",
    readTime: 12,
    difficulty: "intermediate",
    tags: ["KI", "Dokumente", "Analyse", "Automatisierung"],
    views: 2156,
    helpful: 187,
    lastUpdated: "2025-01-05",
  },
  {
    id: "6",
    title: "Zwei-Faktor-Authentifizierung einrichten",
    description: "Schützen Sie Ihren Account mit zusätzlicher Sicherheit durch 2FA.",
    category: "Einstellungen & Sicherheit",
    categoryId: "settings",
    content: "Vollständiger Artikel-Inhalt hier...",
    readTime: 5,
    difficulty: "beginner",
    tags: ["Sicherheit", "2FA", "Authentifizierung"],
    views: 3241,
    helpful: 267,
    lastUpdated: "2025-01-03",
  },
]

export const videoTutorials: VideoTutorial[] = [
  {
    id: "v1",
    title: "Komplette Einführung in Effizienz Praxis",
    description: "Ein umfassender Überblick über alle Funktionen und Möglichkeiten.",
    duration: "18:45",
    thumbnail: "/medical-practice-setup-tutorial.jpg",
    category: "Erste Schritte",
    categoryId: "getting-started",
    views: 12453,
    chapters: [
      { title: "Einleitung", time: "0:00" },
      { title: "Dashboard Übersicht", time: "2:30" },
      { title: "Erste Schritte", time: "5:45" },
      { title: "Wichtige Funktionen", time: "10:20" },
      { title: "Tipps & Tricks", time: "15:00" },
    ],
  },
  {
    id: "v2",
    title: "Team-Management Masterclass",
    description: "Alles über Mitarbeiterverwaltung, Rollen und Berechtigungen.",
    duration: "24:30",
    thumbnail: "/team-management-tutorial.jpg",
    category: "Team & Mitarbeiter",
    categoryId: "team",
    views: 8921,
    chapters: [
      { title: "Team anlegen", time: "0:00" },
      { title: "Rollen verstehen", time: "6:00" },
      { title: "Berechtigungen", time: "12:00" },
      { title: "Best Practices", time: "18:00" },
    ],
  },
  {
    id: "v3",
    title: "Kalender & Terminplanung",
    description: "Effiziente Terminverwaltung und Ressourcenplanung.",
    duration: "15:20",
    thumbnail: "/calendar-scheduling-tutorial.jpg",
    category: "Kalender & Termine",
    categoryId: "calendar",
    views: 7634,
    chapters: [
      { title: "Kalender-Basics", time: "0:00" },
      { title: "Termine erstellen", time: "4:00" },
      { title: "Wiederkehrende Termine", time: "8:00" },
      { title: "Ressourcen verwalten", time: "12:00" },
    ],
  },
  {
    id: "v4",
    title: "KI-Features optimal nutzen",
    description: "Entdecken Sie die Möglichkeiten der integrierten KI-Assistenz.",
    duration: "21:15",
    thumbnail: "/ai-features-tutorial.png",
    category: "KI-Funktionen",
    categoryId: "ai",
    views: 5892,
    chapters: [
      { title: "KI-Übersicht", time: "0:00" },
      { title: "Textgenerierung", time: "5:00" },
      { title: "Dokumentenanalyse", time: "10:00" },
      { title: "Intelligente Vorschläge", time: "15:00" },
    ],
  },
]

export const learningPaths: LearningPath[] = [
  {
    id: "lp1",
    title: "Einsteiger-Kurs",
    description: "Perfekt für neue Nutzer - lernen Sie alle Grundlagen in strukturierten Lektionen.",
    icon: GraduationCap,
    color: "text-blue-500",
    gradient: "from-blue-500 to-cyan-500",
    difficulty: "beginner",
    estimatedTime: "2 Stunden",
    enrolledCount: 1234,
    progress: 0,
    modules: [
      { id: "m1", title: "Willkommen & Überblick", type: "video", duration: "10 min", completed: false },
      { id: "m2", title: "Praxis einrichten", type: "article", duration: "15 min", completed: false },
      { id: "m3", title: "Erste Schritte Quiz", type: "quiz", duration: "5 min", completed: false },
      { id: "m4", title: "Team anlegen", type: "practice", duration: "20 min", completed: false },
      { id: "m5", title: "Dashboard verstehen", type: "video", duration: "12 min", completed: false },
    ],
  },
  {
    id: "lp2",
    title: "Team-Manager Zertifikat",
    description: "Werden Sie zum Experten für Teamverwaltung und Mitarbeiterführung.",
    icon: Users,
    color: "text-emerald-500",
    gradient: "from-emerald-500 to-teal-500",
    difficulty: "intermediate",
    estimatedTime: "4 Stunden",
    enrolledCount: 856,
    progress: 0,
    modules: [
      { id: "m1", title: "Rollen & Berechtigungen", type: "video", duration: "20 min", completed: false },
      { id: "m2", title: "Schichtplanung", type: "article", duration: "25 min", completed: false },
      { id: "m3", title: "Urlaubsmanagement", type: "practice", duration: "30 min", completed: false },
      { id: "m4", title: "Kommunikation im Team", type: "video", duration: "15 min", completed: false },
      { id: "m5", title: "Abschlussprüfung", type: "quiz", duration: "20 min", completed: false },
    ],
  },
  {
    id: "lp3",
    title: "KI Power-User",
    description: "Maximieren Sie die KI-Funktionen für höchste Effizienz in Ihrer Praxis.",
    icon: Brain,
    color: "text-purple-500",
    gradient: "from-purple-500 to-pink-500",
    difficulty: "advanced",
    estimatedTime: "3 Stunden",
    enrolledCount: 543,
    progress: 0,
    modules: [
      { id: "m1", title: "KI-Grundlagen", type: "video", duration: "15 min", completed: false },
      { id: "m2", title: "Textgenerierung meistern", type: "practice", duration: "30 min", completed: false },
      { id: "m3", title: "Dokumentenanalyse", type: "article", duration: "20 min", completed: false },
      { id: "m4", title: "Automatisierung mit KI", type: "video", duration: "25 min", completed: false },
      { id: "m5", title: "KI-Experten Quiz", type: "quiz", duration: "15 min", completed: false },
    ],
  },
]

export const faqs: FAQ[] = [
  {
    id: "faq1",
    question: "Wie kann ich mein Passwort zurücksetzen?",
    answer:
      "Klicken Sie auf der Login-Seite auf 'Passwort vergessen'. Sie erhalten eine E-Mail mit einem Link zum Zurücksetzen. Alternativ können Sie in Ihrem Profil unter Sicherheit Ihr Passwort ändern.",
    category: "Account & Sicherheit",
    helpful: 234,
  },
  {
    id: "faq2",
    question: "Kann ich Mitarbeiter mit eingeschränkten Rechten einladen?",
    answer:
      "Ja, Sie können bei der Einladung eine spezifische Rolle auswählen oder individuelle Berechtigungen vergeben. Gehen Sie zu Einstellungen > Team > Mitarbeiter einladen.",
    category: "Team & Mitarbeiter",
    helpful: 189,
  },
  {
    id: "faq3",
    question: "Wie funktionieren wiederkehrende Termine?",
    answer:
      "Beim Erstellen eines Termins können Sie unter 'Wiederholung' verschiedene Muster wählen: täglich, wöchentlich, monatlich oder benutzerdefiniert. Sie können auch Ausnahmen und ein Enddatum festlegen.",
    category: "Kalender & Termine",
    helpful: 167,
  },
  {
    id: "faq4",
    question: "Welche Dateiformate werden für Dokumente unterstützt?",
    answer:
      "Effizienz Praxis unterstützt PDF, Word (DOC/DOCX), Excel (XLS/XLSX), PowerPoint (PPT/PPTX), Bilder (JPG, PNG, GIF) und viele weitere gängige Formate.",
    category: "Dokumente",
    helpful: 145,
  },
  {
    id: "faq5",
    question: "Ist meine Daten DSGVO-konform gespeichert?",
    answer:
      "Ja, alle Daten werden DSGVO-konform in deutschen Rechenzentren gespeichert. Wir setzen modernste Verschlüsselung ein und Sie haben jederzeit die volle Kontrolle über Ihre Daten.",
    category: "Datenschutz",
    helpful: 198,
  },
  {
    id: "faq6",
    question: "Wie aktiviere ich die KI-Funktionen?",
    answer:
      "KI-Funktionen können unter Einstellungen > Praxis > System aktiviert werden. Nach der Aktivierung finden Sie KI-Assistenten in verschiedenen Bereichen wie Dokumenten, Workflows und dem Dashboard.",
    category: "KI-Funktionen",
    helpful: 156,
  },
]

export const suggestedQuestions = [
  "Wie richte ich meine Praxis ein?",
  "Wie lade ich Teammitglieder ein?",
  "Wie erstelle ich wiederkehrende Termine?",
  "Wie funktioniert die Dokumentenanalyse?",
  "Wie aktiviere ich Zwei-Faktor-Auth?",
  "Wie exportiere ich meine Daten?",
]

export const quickActions = [
  { label: "Mitarbeiter einladen", icon: UserPlus, href: "/team", color: "text-emerald-500" },
  { label: "Termin erstellen", icon: Calendar, href: "/calendar", color: "text-amber-500" },
  { label: "Dokument hochladen", icon: Upload, href: "/documents", color: "text-blue-500" },
  { label: "Workflow anlegen", icon: Workflow, href: "/workflows", color: "text-purple-500" },
]
