import type { AnalyticsTab, AnalyticsItem } from "./types"

export const defaultTabs: AnalyticsTab[] = [
  { id: "overview", name: "Übersicht", order: 1, enabled: true },
  { id: "performance", name: "Leistung", order: 2, enabled: true },
  { id: "charts", name: "Diagramme", order: 3, enabled: true },
]

export const defaultAnalyticsItems: AnalyticsItem[] = [
  {
    id: "kpi-cards",
    title: "KPI Dashboard",
    component: "KPICards",
    enabled: true,
    order: 1,
    category: "performance",
    description: "Key performance indicators",
    chartType: "bar",
    displayIn: "analytics",
    tabIds: ["performance"],
  },
  {
    id: "practice-growth",
    title: "Practice Growth Trends",
    component: "PracticeGrowthChart",
    enabled: true,
    order: 2,
    category: "overview",
    description: "Tasks and revenue over time",
    chartType: "area",
    displayIn: "analytics",
    tabIds: ["overview"],
  },
  {
    id: "task-distribution",
    title: "Task Distribution",
    component: "TaskDistributionChart",
    enabled: true,
    order: 3,
    category: "overview",
    description: "Breakdown of task categories",
    chartType: "pie",
    displayIn: "analytics",
    tabIds: ["overview"],
  },
  {
    id: "team-satisfaction",
    title: "Team Satisfaction",
    component: "TeamSatisfactionChart",
    enabled: true,
    order: 4,
    category: "overview",
    description: "Weekly satisfaction scores",
    chartType: "line",
    displayIn: "analytics",
    tabIds: ["overview"],
  },
  {
    id: "efficiency-metrics",
    title: "Practice Efficiency",
    component: "EfficiencyChart",
    enabled: true,
    order: 5,
    category: "performance",
    description: "Weekly efficiency and throughput",
    chartType: "line",
    displayIn: "analytics",
    tabIds: ["performance"],
  },
  {
    id: "quality-metrics",
    title: "Quality Metrics",
    component: "QualityChart",
    enabled: true,
    order: 6,
    category: "performance",
    description: "Team satisfaction and quality indicators",
    chartType: "area",
    displayIn: "analytics",
    tabIds: ["performance"],
  },
  {
    id: "weekly-tasks",
    title: "Weekly Tasks",
    component: "WeeklyTasksChart",
    enabled: false,
    order: 7,
    category: "charts",
    description: "Completed and pending tasks",
    chartType: "bar",
    displayIn: "analytics",
    tabIds: ["charts"],
  },
  {
    id: "workflow-chart",
    title: "Daily Workflow",
    component: "WorkflowChart",
    enabled: false,
    order: 8,
    category: "charts",
    description: "Task status throughout the day",
    chartType: "area",
    displayIn: "analytics",
    tabIds: ["charts"],
  },
  {
    id: "revenue-analysis",
    title: "Revenue Analysis",
    component: "RevenueChart",
    enabled: false,
    order: 9,
    category: "charts",
    description: "Monthly revenue trends",
    chartType: "line",
    displayIn: "analytics",
    tabIds: ["charts"],
  },
]
