import type { MetadataRoute } from "next"

export default function robots(): MetadataRoute.Robots {
  const baseUrl = process.env.NEXT_PUBLIC_APP_URL || "https://effizienz-praxis.de"

  return {
    rules: [
      {
        userAgent: "*",
        allow: [
          "/",
          "/features/",
          "/blog/",
          "/effizienz",
          "/preise",
          "/demo",
          "/alle-funktionen",
          "/selbst-check",
          "/ueber-uns",
          "/kontakt",
          "/karriere",
          "/sicherheit",
          "/updates",
          "/whats-new",
          "/help",
          "/impressum",
          "/datenschutz",
          "/agb",
          "/cookies",
          "/auth/login",
          "/auth/sign-up",
        ],
        disallow: [
          "/api/",
          "/super-admin/",
          "/dashboard/",
          "/team/",
          "/settings/",
          "/protocols/",
          "/analytics/",
          "/calendar/",
          "/todos/",
          "/workflows/",
          "/documents/",
          "/knowledge/",
          "/goals/",
          "/hiring/",
          "/zeiterfassung/",
          "/dienstplan/",
          "/hygiene/",
          "/hygieneplan/",
          "/cirs/",
          "/profile/",
          "/onboarding/",
          "/messages/",
          "/communication/",
          "/contacts/",
          "/devices/",
          "/rooms/",
          "/arbeitsmittel/",
          "/arbeitsplaetze/",
          "/organigramm/",
          "/skills/",
          "/training/",
          "/wellbeing/",
          "/leadership/",
          "/leitbild/",
          "/responsibilities/",
          "/mitarbeitergespraeche/",
          "/inventory/",
          "/tickets/",
          "/surveys/",
          "/strategy-journey/",
          "/perma-v/",
          "/practice/",
          "/practice-insights/",
          "/competitor-analysis/",
          "/igel/",
          "/igel-analysis/",
          "/roi-analysis/",
          "/analysis/",
          "/wunschpatient/",
          "/academy/",
          "/auth/callback",
          "/auth/pending-approval",
          "/auth/reset-password",
          "/auth/register",
          "/auth/sign-up-success",
          "/questionnaire/",
          "/survey/",
        ],
      },
      {
        userAgent: "GPTBot",
        disallow: ["/"],
      },
      {
        userAgent: "CCBot",
        disallow: ["/"],
      },
    ],
    sitemap: `${baseUrl}/sitemap.xml`,
  }
}
