import {
  Brain,
  TrendingUp,
  BarChart3,
  Users,
  Layers,
  GraduationCap,
  Briefcase,
  Network,
  Calendar,
  CheckSquare,
  Target,
  Workflow,
  ClipboardList,
  BookOpen,
  FolderOpen,
  Mic,
  Phone,
  Map,
  Heart,
  Lightbulb,
  Search,
  UserPlus,
  DoorOpen,
  Package,
  MonitorCheck,
  Settings,
  CalendarClock,
  Clock,
  ShieldCheck,
  ShieldAlert,
  BookOpenCheck,
  Crown,
  Smile,
  MessageSquare,
  ClipboardCheck,
  Cpu,
  LayoutDashboard,
  Clipboard,
  ClipboardPenLine,
  Wrench,
  type LucideIcon,
} from "lucide-react"

export interface Feature {
  icon: LucideIcon
  title: string
  description: string
  color: string
  image: string
  category: string
  link: string
}

export const features: Feature[] = [
  // Übersicht & Analyse
  {
    icon: LayoutDashboard,
    title: "Dashboard",
    description: "Zentrale Übersicht aller wichtigen Praxis-Kennzahlen",
    color: "bg-blue-500/10 text-blue-600",
    image: "/features/dashboard-overview-blue-modern.jpg",
    category: "analyse",
    link: "/features/dashboard",
  },
  {
    icon: Brain,
    title: "KI-Praxisanalyse",
    description: "Intelligente Stärken-Schwächen-Analyse mit Optimierungsvorschlägen",
    color: "bg-blue-500/10 text-blue-600",
    image: "/ai-brain-analysis-medical-dashboard-blue-modern.jpg",
    category: "analyse",
    link: "/features/ai-praxisanalyse",
  },
  {
    icon: TrendingUp,
    title: "Praxis-Auswertung",
    description: "Analytics mit KV-Abrechnung und KPI-Dashboards",
    color: "bg-emerald-500/10 text-emerald-600",
    image: "/analytics-charts-dashboard-green-medical-practice.jpg",
    category: "analyse",
    link: "/analytics",
  },
  {
    icon: Clipboard,
    title: "Schwarzes Brett",
    description: "Interne Mitteilungen, Ankündigungen und Team-Kommunikation",
    color: "bg-orange-500/10 text-orange-600",
    image: "/features/schwarzes-brett-bulletin-orange.jpg",
    category: "analyse",
    link: "/features/schwarzes-brett",
  },
  {
    icon: BarChart3,
    title: "Praxis-Journal",
    description: "Tägliche Dokumentation und Auswertungen",
    color: "bg-teal-500/10 text-teal-600",
    image: "/medical-journal-documentation-teal-modern-dashboar.jpg",
    category: "analyse",
    link: "/features/praxis-journal",
  },
  // Team & Personal
  {
    icon: Users,
    title: "Team-Management",
    description: "Mitarbeiter, Urlaub, Krankmeldungen & Organigramm",
    color: "bg-cyan-500/10 text-cyan-600",
    image: "/team-management-organization-chart-people-cyan.jpg",
    category: "team",
    link: "/features/team-management",
  },
  {
    icon: Layers,
    title: "Skills-Management",
    description: "Kompetenzen erfassen, bewerten und Entwicklungsziele setzen",
    color: "bg-violet-500/10 text-violet-600",
    image: "/skills-competency-matrix-violet-modern-dashboard.jpg",
    category: "team",
    link: "/features/skills-management",
  },
  {
    icon: GraduationCap,
    title: "Fortbildung",
    description: "Zertifikate, Schulungen, Budget und Kalender verwalten",
    color: "bg-rose-500/10 text-rose-600",
    image: "/training-education-certificate-rose-modern-dashboa.jpg",
    category: "team",
    link: "/features/fortbildung",
  },
  {
    icon: Briefcase,
    title: "Recruiting-System",
    description: "Hiring-Pipeline mit Bewerbermanagement und KI",
    color: "bg-orange-500/10 text-orange-600",
    image: "/recruiting-hiring-job-candidates-orange-profession.jpg",
    category: "team",
    link: "/features/recruiting",
  },
  {
    icon: BookOpenCheck,
    title: "Academy",
    description: "E-Learning Plattform mit Kursen und Onboarding",
    color: "bg-indigo-500/10 text-indigo-600",
    image: "/features/academy-elearning-indigo.jpg",
    category: "team",
    link: "/features/academy",
  },
  {
    icon: Crown,
    title: "Leadership",
    description: "Führungskompetenzen entwickeln und Teamkultur stärken",
    color: "bg-amber-500/10 text-amber-600",
    image: "/features/leadership-development-amber.jpg",
    category: "team",
    link: "/features/leadership",
  },
  {
    icon: Smile,
    title: "Mitarbeiter-Wellbeing",
    description: "Teamzufriedenheit messen und Wohlbefinden fördern",
    color: "bg-green-500/10 text-green-600",
    image: "/features/wellbeing-team-satisfaction-green.jpg",
    category: "team",
    link: "/features/wellbeing",
  },
  {
    icon: MessageSquare,
    title: "Mitarbeitergespräche",
    description: "Strukturierte Feedbackgespräche planen und dokumentieren",
    color: "bg-blue-500/10 text-blue-600",
    image: "/features/mitarbeitergespraeche-feedback-blue.jpg",
    category: "team",
    link: "/features/mitarbeitergespraeche",
  },
  {
    icon: ClipboardCheck,
    title: "Selbst-Check",
    description: "Persönliche Selbsteinschätzung und Entwicklungsziele",
    color: "bg-purple-500/10 text-purple-600",
    image: "/features/selbst-check-assessment-purple.jpg",
    category: "team",
    link: "/features/selbst-check",
  },
  {
    icon: Network,
    title: "Organigramm",
    description: "Visuelle Darstellung der Praxisstruktur",
    color: "bg-sky-500/10 text-sky-600",
    image: "/organization-structure-chart-sky-blue-modern.jpg",
    category: "team",
    link: "/features/organigramm",
  },
  // Planung & Organisation
  {
    icon: CalendarClock,
    title: "Dienstplan",
    description: "Schichtplanung, Dienste und Vertretungen organisieren",
    color: "bg-teal-500/10 text-teal-600",
    image: "/features/dienstplan-shift-planning-teal.jpg",
    category: "planung",
    link: "/features/dienstplan",
  },
  {
    icon: Clock,
    title: "Zeiterfassung",
    description: "Arbeitszeiten, Pausen und Überstunden digital erfassen",
    color: "bg-slate-500/10 text-slate-600",
    image: "/features/zeiterfassung-time-tracking-slate.jpg",
    category: "planung",
    link: "/features/zeiterfassung",
  },
  {
    icon: Calendar,
    title: "Kalender",
    description: "Termine, Urlaub und Abwesenheiten planen",
    color: "bg-blue-500/10 text-blue-600",
    image: "/calendar-scheduling-planning-blue-modern-dashboard.jpg",
    category: "planung",
    link: "/features/kalender",
  },
  {
    icon: CheckSquare,
    title: "Aufgaben",
    description: "To-Do Listen mit Prioritäten und Fristen",
    color: "bg-green-500/10 text-green-600",
    image: "/tasks-todo-checklist-green-modern-dashboard.jpg",
    category: "planung",
    link: "/features/aufgaben",
  },
  {
    icon: Target,
    title: "Ziele",
    description: "OKRs und Zielverfolgung für die Praxis",
    color: "bg-amber-500/10 text-amber-600",
    image: "/goals-dashboard-with-progress-bars-and-okr-trackin.jpg",
    category: "planung",
    link: "/features/ziele",
  },
  {
    icon: Workflow,
    title: "Workflows",
    description: "Automatisierte Abläufe mit Vorlagen und Aufgaben",
    color: "bg-purple-500/10 text-purple-600",
    image: "/workflow-automation-checklist-tasks-purple-modern.jpg",
    category: "planung",
    link: "/features/workflows-checklisten",
  },
  {
    icon: ClipboardList,
    title: "Zuständigkeiten",
    description: "Verantwortlichkeiten klar definieren und verteilen",
    color: "bg-indigo-500/10 text-indigo-600",
    image: "/responsibilities-assignments-indigo-modern-dashboa.jpg",
    category: "planung",
    link: "/features/zustaendigkeiten",
  },
  // Wissen & Dokumente
  {
    icon: BookOpen,
    title: "Wissen & QM",
    description: "Wissensdatenbank für QM und SOPs mit KI-Suche",
    color: "bg-pink-500/10 text-pink-600",
    image: "/knowledge-management-documents-library-pink-modern.jpg",
    category: "wissen",
    link: "/features/wissen-qm",
  },
  {
    icon: ShieldCheck,
    title: "Hygieneplan",
    description: "RKI-konforme Hygienepläne erstellen und verwalten",
    color: "bg-emerald-500/10 text-emerald-600",
    image: "/features/hygieneplan-rki-emerald.jpg",
    category: "wissen",
    link: "/features/hygieneplan",
  },
  {
    icon: ShieldAlert,
    title: "CIRS-Meldungen",
    description: "Verbesserungsmeldungen und Beinahe-Fehler systematisch erfassen",
    color: "bg-red-500/10 text-red-600",
    image: "/features/cirs-incident-reporting-red.jpg",
    category: "wissen",
    link: "/features/cirs-meldungen",
  },
  {
    icon: FolderOpen,
    title: "Dokumente",
    description: "Dokumentenmanagement mit Versionierung",
    color: "bg-slate-500/10 text-slate-600",
    image: "/documents-files-folder-slate-modern-dashboard.jpg",
    category: "wissen",
    link: "/features/dokumente",
  },
  {
    icon: Mic,
    title: "Gesprächsprotokoll",
    description: "Meetings dokumentieren mit KI-Zusammenfassung",
    color: "bg-red-500/10 text-red-600",
    image: "/meeting-protocol-recording-red-modern-dashboard.jpg",
    category: "wissen",
    link: "/features/gesprächsprotokoll",
  },
  {
    icon: Phone,
    title: "Kontakte",
    description: "Lieferanten, Partner und wichtige Kontakte",
    color: "bg-gray-500/10 text-gray-600",
    image: "/contacts-address-book-gray-modern-dashboard.jpg",
    category: "wissen",
    link: "/features/kontakte",
  },
  {
    icon: ClipboardPenLine,
    title: "Umfragen",
    description: "Patienten- und Mitarbeiterbefragungen erstellen und auswerten",
    color: "bg-teal-500/10 text-teal-600",
    image: "/features/umfragen-surveys-teal.jpg",
    category: "praxis",
    link: "/features/umfragen",
  },
  // Strategie
  {
    icon: Map,
    title: "Strategiepfad",
    description: "Praxisentwicklung strategisch planen",
    color: "bg-emerald-500/10 text-emerald-600",
    image: "/strategy-roadmap-planning-emerald-green-modern-das.jpg",
    category: "strategie",
    link: "/features/strategiepfad",
  },
  {
    icon: Heart,
    title: "Leitbild",
    description: "Vision, Mission und Werte definieren",
    color: "bg-rose-500/10 text-rose-600",
    image: "/mission-vision-values-rose-pink-modern-dashboard.jpg",
    category: "strategie",
    link: "/features/leitbild",
  },
  {
    icon: Lightbulb,
    title: "IGeL & ROI-Analyse",
    description: "Wirtschaftlichkeitsanalysen mit Szenarien",
    color: "bg-amber-500/10 text-amber-600",
    image: "/roi-analysis-financial-charts-amber-business.jpg",
    category: "strategie",
    link: "/features/igel-roi-analyse",
  },
  {
    icon: Search,
    title: "Konkurrenzanalyse",
    description: "SWOT-Analyse und strategische Positionierung",
    color: "bg-indigo-500/10 text-indigo-600",
    image: "/competitor-analysis-swot-strategy-indigo-business.jpg",
    category: "strategie",
    link: "/features/konkurrenzanalyse",
  },
  {
    icon: UserPlus,
    title: "Wunschpatient",
    description: "Ideale Patientenprofile definieren und erreichen",
    color: "bg-cyan-500/10 text-cyan-600",
    image: "/ideal-patient-profile-cyan-modern-dashboard.jpg",
    category: "strategie",
    link: "/features/wunschpatient",
  },
  // Praxis & Infrastruktur
  {
    icon: Cpu,
    title: "Geräte",
    description: "Medizingeräte, Einweisungen und Wartung verwalten",
    color: "bg-cyan-500/10 text-cyan-600",
    image: "/features/geraete-medical-devices-cyan.jpg",
    category: "praxis",
    link: "/features/geraete",
  },
  {
    icon: DoorOpen,
    title: "Räume",
    description: "Raumplanung und -verwaltung",
    color: "bg-stone-500/10 text-stone-600",
    image: "/rooms-office-space-stone-modern-dashboard.jpg",
    category: "praxis",
    link: "/features/räume",
  },
  {
    icon: Wrench,
    title: "Arbeitsmittel",
    description: "Arbeitsmittel und Ausstattung verwalten",
    color: "bg-orange-500/10 text-orange-600",
    image: "/features/arbeitsmittel-equipment-orange.jpg",
    category: "praxis",
    link: "/features/arbeitsmittel",
  },
  {
    icon: Package,
    title: "Material",
    description: "Materialbestand, Bestellungen und Verbrauch verwalten",
    color: "bg-lime-500/10 text-lime-600",
    image: "/features/material-inventory-lime.jpg",
    category: "praxis",
    link: "/features/material",
  },
  {
    icon: MonitorCheck,
    title: "Arbeitsplätze",
    description: "Arbeitsplätze und Stationen konfigurieren",
    color: "bg-blue-500/10 text-blue-600",
    image: "/placeholder.svg?height=200&width=400",
    category: "praxis",
    link: "/features/arbeitsplätze",
  },
  // System & Sicherheit
  {
    icon: Settings,
    title: "Einstellungen",
    description: "Praxis- und Benutzereinstellungen anpassen",
    color: "bg-gray-500/10 text-gray-600",
    image: "/placeholder.svg?height=200&width=400",
    category: "system",
    link: "/features/einstellungen",
  },
]
